<!-- SiteCatalyst code version: H.25.3.
Copyright 1996-2013 Adobe, Inc. All Rights Reserved
More info available at http://www.omniture.com -->
<img src="http://eltiempo.112.2o7.net/b/ss/eltiempoeltiempomovil,eltiempoglobal/5/H.25.3--WAP/489?pageName=<?php print $pageName?>&ch=<?php print $channel?>&r=<?php print $referer; ?>" height="1" width="1" border="0" alt="" style="position:absolute"></img>
<!-- End SiteCatalyst code version: H.25.3. -->
