<footer>
    <div class="terminos">
        <h3 class="logo_footer"><a target="_blank" href="http://m.eltiempo.com"></a></h3>
        <a target="_blank" href="http://m.eltiempo.com/terminos-condiciones">Ver t&eacute;rminos y condiciones</a>
    </div>
    <div class="copy">
        <p>COPYRIGHT © <?php print date('Y');?> EL TIEMPO Casa Editorial.</p>
        <p>Prohibida su reproducci&oacute;n total o parcial, as&iacute; como su traducci&oacute;n a cualquier idioma sin autorizaci&oacute;n escrita de su titular. ELTIEMPO.com todas las noticias principales de Colombia y el Mundo</p>
    </div>
</footer>