<section class="modulo registraduria">
    <div class="ac-container">
        <div> <a class="noticias">REGISTRADURIA</a>
            <article>
                    <img src="<?php echo $this->basePath(); ?>/images/ico-registraduria.png" alt="registraduria">
                    <p>Encuentre aqu&iacute; su lugar de votaci&oacute;n ingresando su n&uacute;mero de identificaci&oacute;n.</p>
                    <a class="btn-servicios" target="_blank" href="http://www.registraduria.gov.co/servicios/censo.htm">BUSCA TU PUESTO</a>
            </article>
        </div>
    </div>
</section>
