<header id="header-mundial">
    <div class="top-bar">
        <ul>
            <li><p>Un especial de:</p></li>
            <li><h2 class="logo-ET"><a href="http://m.eltiempo.com" target="_blank">ELTIEMPO.COM</a></h2></li>
            <li><p>-</p></li>
            <li><h1 class="logo-FR"><a href="http://m.futbolred.com" target="_blank">FUTBOLRED.COM</a></h1></li>
            <li class="compartir">
                <a class="btn_compartir">Compartir</a>
                <ul class="redes-header">
                        <li><a class="facebook" rel="nofollow" href="http://www.facebook.com/sharer.php?u=<?php print $url;?>" target="_blank">Facebook</a></li>
                        <li><a class="twitter" rel="nofollow" href="https://twitter.com/share?url=<?php print $url; ?>&via=ELTIEMPO&text=<?php print $titulo; ?>" target="_blank">Twitter</a></li>
                </ul>
            </li>
       </ul>
    </div>
    <div class="menu">
        <ul>
            <li class="btn-menu"><a href="#">btn</a></li>
            <li class="logoEspecial"><h1><div style="display: none;">Mundial Brasil 2014</div><a href="http://m.eltiempo.com/mundial-brasil-2014">Copa mundial Brasil 2014</a></h1></li>
        </ul>
    </div>
</header>