<nav class="container-menu">
    <ul>
        <li><a class="logo_nav" href="#">Logo</a></li>
        <li><a href="/brazil-2014-dev/calendario">Calendario</a></li>
        <li><a href="/brazil-2014-dev#colombia">Colombia</a></li>
        <li><a href="/brazil-2014-dev#mundo">Equipos del Mundo</a></li>
        <li><a href="/brazil-2014-dev#opinion">Opinión</a></li>
        <li><a href="/brazil-2014-dev#multimedia">Multimedia</a></li>
        <li><a href="/brazil-2014-dev#colombia">Redes</a></li>
        <li><a href="/brazil-2014-dev#curiosidades">Curiosidades</a></li>
    </ul>
</nav>