<section class="modulo <?php print $claseExtra; ?>" id="<?php print $claseExtra; ?>">
    <div class="ac-container">	
        <div>
            <input id="<?php print $idModulo; ?>" name="<?php print $clase;?>" type="checkbox" />
            <label for="<?php print $idModulo; ?>" ><h3><?php print $titulo; ?></h3></label>
            <?php print $this->partial('mundial/cargar-mas/cargar-mas', array('seccion' => $procede, 'procede' => $procede,));?>
        </div>
    </div>                  
</section>