<meta property="og:title" content="<?php echo $titulo; ?>" />
<meta property="og:type" content="website" />
<meta property="og:url" content="<?php echo $enlace; ?>" />
<meta property="og:description" content="<?php echo $descripcion; ?>" />
<meta property="og:site_name" content="<?php echo $name?>"/>
<meta property="og:image" content="<?php echo $imagen; ?>" />
<meta property="fb:admins" content="100002279652972" />