<aside class="<?php print $clasecss;?>">
    <p>Publicidad</p>
    <div>
        <script type="text/javascript">
            sas_pageid      = '<?php print $idPagina; ?>';        // Página : Movil_El_Tiempo/home
            sas_formatid    = '<?php print $idEspacio; ?>';                        // Formato : Movil Banner Inferior 0x0
            sas_target      = 'seccion=<?php print $target; ?>';                                     // Segmentación
            sasmobile(sas_pageid,sas_formatid,sas_target);
        </script>
    </div>
</aside>