<div class="redes">
    <ul>
        compartir
        <a class="btnR2" rel="nofollow" href="http://www.facebook.com/sharer.php?u=<?php print $url; ?>" target="_blank">FACEBOOK</a>
        <a class="btnR3" rel="nofollow" href="https://twitter.com/share?url=<?php print $url; ?>&via=ELTIEMPO&text=<?php print $titulo; ?>" target="_blank">TWITTER</a>
        <!--<a class="btnR4" rel="nofollow" href='https://plus.google.com/share?url="<?php print $url; ?>"' target="_blank">CORREO</a>-->
    </ul>
</div>
