<section class="social">
    <div class="compartir">
        <ul>
            <li><p>Compartir</p></li>
            <li><a class="facebook" rel="nofollow" href="http://www.facebook.com/sharer.php?u=<?php print $url;?>" target="_blank">Facebook</a></li>
            <li><a class="twitter" rel="nofollow" href="https://twitter.com/share?url=<?php print $url; ?>&via=ELTIEMPO&text=<?php print $titulo; ?>" target="_blank">Twitter</a></li>
            <!--<li><a class="correo" rel="nofollow" href='https://plus.google.com/share?url="<?php print $url; ?>"' target="_blank">Correo</a></li>-->
        </ul>
    </div>
</section>