<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8">
        <title>ELTIEMPO.com</title>
        <meta name="description" content="">
        <meta name="author" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- Favicons -->
        <link rel="shortcut icon" href="/images/favicon.ico">
        <link rel="apple-touch-icon" href="/images/apple-touch-icon.png">
        <link rel="apple-touch-icon" sizes="72x72" href="/images/apple-touch-icon-72x72.png">
        <link rel="apple-touch-icon" sizes="114x114" href="/images/apple-touch-icon-114x114.png">
        <!-- CSS Styles -->
        <link rel="stylesheet"  href="/mundial-brasil-2014/css/css404Movil/page_404.css">
	<link rel="stylesheet" href="/mundial-brasil-2014/css/css404Movil/reset.css" type="text/css" media="screen" />
	<link rel="stylesheet" href="/mundial-brasil-2014/css/css404Movil/flexslider.css" type="text/css" media="screen" />
	<link rel="stylesheet" href="/mundial-brasil-2014/css/css404Movil/generales.css" type="text/css" media="screen" />
	<link rel="stylesheet" href="/mundial-brasil-2014/css/css404Movil/home.css" type="text/css" media="screen" />
	<link href="/mundial-brasil-2014/fonts/stylesheet.css" rel="stylesheet" />
	<!-- Javascript -->
	<script src="/mundial-brasil-2014/js/js404Movil/modernizr.js"></script>
    </head>
    <body>
        <div id="contenedor-M14">
            <section data-role="content" class="content_main">
                <article class="error-404">
                    <img class="img-error" src="/mundial-brasil-2014/img/img404Movil/404error.gif" alt="404 error" />
                    <h1>
                            La página que solicitas no está disponible.
                    </h1>
                    <h2>
                            No hemos encontrado la página que estás buscando, puede que esté temporalmente no disponible o que haya sido eliminada.
                    </h2>
                    <a href="/mundial-brasil-2014" class="btn-volver">VOLVER AL INICIO</a>
                </article>
            </section>
        </div>
    </body>
</html>