<div class="secciones seleccionColombia">
    <div class="overlay"></div>

    <?php print $this->pauta('9703', '432764', 'pauta'); ?>


    <section class="contHomeSeccion seleccionColombia">
        <div class="tit_homeSeccion seleccionColombia">
            <h3 class="tituloHomeSeccion">Selección Colombia</h3>
        </div>
        <?php print $this->redesSociales($compartir, 'redes-sociales-multimedia');?>	
        <?php
            $i=0;
            foreach($notas as $nota):
                print $this->notasPpalSecciones($nota,$i);
                $i++;
            endforeach;
        ?>
    </section>


    <div class="btnSeleccionColombia"><h3><a href="/brazil-2014-dev/ficha-de-equipo/colombia">ver ficha equipo selección colombia</a></h3></div>

    <section class="masnoticia-M14 seleccionColombia">
        <div class="titulo-top seleccionColombia">
            <h3>Todo sobre selección colombia</h3>
        </div>
        <?php print $this->partial('mundial/cargar-mas/cargar-mas', array('seccion' => 'seleccion-colombia', 'procede' => 'seleccion-colombia',)); ?>					
    </section>

    <section class="masnoticia-M14 curiosidades">
        <div class="titulo-top">
            <h3>lo más visto</h3>
        </div>
        <?php 
            for($i=0; $i<$maximoVistas; $i++):
                print $this->notas($vistas[$i], 'row1');
            endfor;
        ?>				
    </section>

    <?php print $this->otrosTemas($otrosTemas, 'colombia', 'Selección Colombia');?>
</div>