<div class="secciones videoFotos">
    <div class="overlay"></div>

    <?php print $this->pauta('9703', '432762', 'pauta'); ?>

    <section class="contHomeSeccion videoFotos">
        <div class="tit_homeSeccion videoFotos">
            <h3 class="tituloHomeSeccion"> video y Fotos</h3>
        </div>
        <?php print $this->redesSociales($compartir, 'redes-sociales-multimedia');?>	
        <?php
            $i=0;
            foreach($notas as $nota):
                print $this->notasPpalSecciones($nota,$i);
                $i++;
            endforeach;
        ?>
    </section>


    <section class="masnoticia-M14 videoFotos">
        <div class="titulo-top videoFotos">
            <h3>Todo sobre videoFotos</h3>
        </div>
        <?php print $this->partial('mundial/cargar-mas/cargar-mas', array('seccion' => 'seleccion-colombia', 'procede' => 'seleccion-colombia',)); ?>					
    </section>


    <section class="masnoticia-M14 curiosidades">
        <div class="titulo-top">
            <h3>lo más visto</h3>
        </div>
        <?php 
            for($i=0; $i<$maximoVistas; $i++):
                print $this->notas($vistas[$i], 'row1');
            endfor;
        ?>				
    </section>

    <section>
        Espacio para encuesta 

    </section>

    <?php print $this->otrosTemas($otrosTemas, 'colombia', 'Selección Colombia');?>

</div>