<!-- CSS Styles -->
<link rel="stylesheet" href="/mundial-brasil-2014/css/cssCalendario/resetCalendario.css" type="text/css" media="screen" />
<link rel="stylesheet" href="/mundial-brasil-2014/css/cssCalendario/flexsliderCalendario.css" type="text/css" media="screen" />
<link rel="stylesheet" href="/mundial-brasil-2014/css/cssCalendario/generalesCalendario.css" type="text/css" media="screen" />
<link rel="stylesheet" href="/mundial-brasil-2014/css/cssCalendario/homeCalendario.css" type="text/css" media="screen" />


<!-- Styles calenbdario desktop 
================================================== -->
<link rel="stylesheet" href="/mundial-brasil-2014/css/cssCalendario/resetCalendario.css">
<link rel="stylesheet" href="/mundial-brasil-2014/css/cssCalendario/styleCalendario.css">
<link rel="stylesheet" href="/mundial-brasil-2014/css/cssCalendario/styleCalendario2.css">
<link rel="stylesheet" type="text/css" href="/mundial-brasil-2014/css/cssCalendario/New_pronosticoCalendario.css">

<!-- Javascript -->
<script src="/mundial-brasil-2014/js/jsCalendario/modernizr.js"></script>

<title>Grupos Mundial Brasil 2014</title>  
<meta name="description" content="Información actualizada de los Grupos de equipos del mundial de Brasil 2014 y el calendario de partidos de cada uno de los grupos de Mundial.">
<meta name="keywords" content="calendario, cronograma, partidos, horas, estadios, mundial, brasil, futbol, deportes, mundial, grupos">

<meta property="og:title" content="Tabla de Posiciones Mundial Brasil 2014" />
<meta property="og:type" content="website" />
<meta property="og:url" content="http://m.eltiempo.com/mundial-brasil-2014/calendario/grupos" />
<meta property="og:description" content="Vea aquí la información de la fase de grupos en el especial multimedia del Mundial Brasil 2014" />
<meta property="og:image" content="http://m.eltiempo.com/mundial-brasil-2014/img/imagen_compartir.jpg" />
<meta property="fb:admins" content="100002279652972" />
</head>

<body>
    <div class="container">
        <div class="content">

            <?php print $this->header(); ?>

            <div class="secciones">
                <div id="overlay" class="overlay"></div>
                <section class="tabla_clasificacionM">
                    <div class="tit_tablaM">
                        <h3 class="tituloCalen">GRUPOS</h3>
                    </div>
                </section>
                <section class="social">
                    <div class="compartir">
                        <ul>
                            <li><p>Compartir</p></li>
                            <li><a class="facebook" href="#">Facebook</a></li>
                            <li><a class="twitter" href="#">Twitter</a></li>
                            <li><a class="correo" href="#">Correo</a></li>
                        </ul>
                    </div>
                </section>

                <!----------------- POPUPS GRUPO A -------------------------->
                <div id="a1" class="reveal-modal small">
                    <p class="dialogoTit A">A</p>
                    <div class="grupo a" style="z-index: 1;">                                        
                        <div class="tabla-completa">                        
                            <div class="filaDialogo">
                                <ul class="tabla-pais3 bra">
                                    <li>
                                        <span class="pais-p bra"></span>
                                        BRA
                                    </li>
                                </ul>
                                <ul class="marcador3">
                                    <li>0</li>
                                    <li>0</li>
                                </ul>
                                <ul class="tabla-pais3 cro">
                                    <li>
                                        <span class="pais-p cro"></span>
                                        CRO
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="horaDialogo">
                            <h4>12/06 17:00</h4>
                            <h4>Sao Paulo</h4>
                        </div>              
                    </div>  
                    <a class="close-reveal-modal">&#215;</a>
                </div>
                <div id="a2" class="reveal-modal small">
                    <p class="dialogoTit A">A</p>
                    <div class="grupo a" style="z-index: 1;">                                        
                        <div class="tabla-completa">                        
                            <div class="filaDialogo">
                                <ul class="tabla-pais3 mex">
                                    <li>
                                        <span class="pais-p mex"></span>
                                        MEX
                                    </li>
                                </ul>
                                <ul class="marcador3">
                                    <li>0</li>
                                    <li>0</li>
                                </ul>
                                <ul class="tabla-pais3 cam">
                                    <li>
                                        <span class="pais-p cam"></span>
                                        CAM
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="horaDialogo">
                            <h4>13/06 13:00</h4>
                            <h4>Natal</h4>
                        </div>              
                    </div>  
                    <a class="close-reveal-modal">&#215;</a>
                </div>
                <div id="a3" class="reveal-modal small">
                    <p class="dialogoTit A">A</p>
                    <div class="grupo a" style="z-index: 1;">                                        
                        <div class="tabla-completa">                        
                            <div class="filaDialogo">
                                <ul class="tabla-pais3 bra">
                                    <li>
                                        <span class="pais-p bra"></span>
                                        BRA
                                    </li>
                                </ul>
                                <ul class="marcador3">
                                    <li>0</li>
                                    <li>0</li>
                                </ul>
                                <ul class="tabla-pais3 mex">
                                    <li>
                                        <span class="pais-p mex"></span>
                                        MEX
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="horaDialogo">
                            <h4>17/06 16:00</h4>
                            <h4>Fortaleza</h4>
                        </div>              
                    </div>  
                    <a class="close-reveal-modal">&#215;</a>
                </div>
                <div id="a4" class="reveal-modal small">
                    <p class="dialogoTit A">A</p>
                    <div class="grupo a" style="z-index: 1;">                                        
                        <div class="tabla-completa">                        
                            <div class="filaDialogo">
                                <ul class="tabla-pais3 cam">
                                    <li>
                                        <span class="pais-p cam"></span>
                                        CAM
                                    </li>
                                </ul>
                                <ul class="marcador3">
                                    <li>0</li>
                                    <li>0</li>
                                </ul>
                                <ul class="tabla-pais3 cro">
                                    <li>
                                        <span class="pais-p cro"></span>
                                        CRO
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="horaDialogo">
                            <h4>18/06 16:00</h4>
                            <h4>Manaos</h4>
                        </div>              
                    </div>  
                    <a class="close-reveal-modal">&#215;</a>
                </div>
                <div id="a5" class="reveal-modal small">
                    <p class="dialogoTit A">A</p>
                    <div class="grupo a" style="z-index: 1;">                                        
                        <div class="tabla-completa">                        
                            <div class="filaDialogo">
                                <ul class="tabla-pais3 bra">
                                    <li>
                                        <span class="pais-p bra"></span>
                                        BRA
                                    </li>
                                </ul>
                                <ul class="marcador3">
                                    <li>0</li>
                                    <li>0</li>
                                </ul>
                                <ul class="tabla-pais3 cam">
                                    <li>
                                        <span class="pais-p cam"></span>
                                        CAM
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="horaDialogo">
                            <h4>23/06 17:00</h4>
                            <h4>Brasilia</h4>
                        </div>              
                    </div>  
                    <a class="close-reveal-modal">&#215;</a>
                </div>
                <div id="a6" class="reveal-modal small">
                    <p class="dialogoTit A">A</p>
                    <div class="grupo a" style="z-index: 1;">                                        
                        <div class="tabla-completa">                        
                            <div class="filaDialogo">
                                <ul class="tabla-pais3 cro">
                                    <li>
                                        <span class="pais-p cro"></span>
                                        CRO
                                    </li>
                                </ul>
                                <ul class="marcador3">
                                    <li>0</li>
                                    <li>0</li>
                                </ul>
                                <ul class="tabla-pais3 mex">
                                    <li>
                                        <span class="pais-p mex"></span>
                                        MEX
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="horaDialogo">
                            <h4>23/06 17:00</h4>
                            <h4>Recife</h4>
                        </div>              
                    </div>  
                    <a class="close-reveal-modal">&#215;</a>
                </div>

                <!----------------- POPUPS GRUPO b -------------------------->
                <div id="b1" class="reveal-modal small">
                    <p class="dialogoTit B">B</p>
                    <div class="grupo b" style="z-index: 1;">                                        
                        <div class="tabla-completa">                        
                            <div class="filaDialogo">
                                <ul class="tabla-pais3 esp">
                                    <li>
                                        <span class="pais-p esp"></span>
                                        ESP
                                    </li>
                                </ul>
                                <ul class="marcador3">
                                    <li>0</li>
                                    <li>0</li>
                                </ul>
                                <ul class="tabla-pais3 hol">
                                    <li>
                                        <span class="pais-p hol"></span>
                                        HOL
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="horaDialogo">
                            <h4>13/06 16:00</h4>
                            <h4>Salvador</h4>
                        </div>              
                    </div>  
                    <a class="close-reveal-modal">&#215;</a>
                </div>
                <div id="b2" class="reveal-modal small">
                    <p class="dialogoTit B">B</p>
                    <div class="grupo b" style="z-index: 1;">                                        
                        <div class="tabla-completa">                        
                            <div class="filaDialogo">
                                <ul class="tabla-pais3 chi">
                                    <li>
                                        <span class="pais-p chi"></span>
                                        CHI
                                    </li>
                                </ul>
                                <ul class="marcador3">
                                    <li>0</li>
                                    <li>0</li>
                                </ul>
                                <ul class="tabla-pais3 aus">
                                    <li>
                                        <span class="pais-p aus"></span>
                                        AUS
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="horaDialogo">
                            <h4>13/06 18:00</h4>
                            <h4>Cuiabá</h4>
                        </div>              
                    </div>  
                    <a class="close-reveal-modal">&#215;</a>
                </div>
                <div id="b3" class="reveal-modal small">
                    <p class="dialogoTit B">B</p>
                    <div class="grupo b" style="z-index: 1;">                                        
                        <div class="tabla-completa">                        
                            <div class="filaDialogo">
                                <ul class="tabla-pais3 esp">
                                    <li>
                                        <span class="pais-p esp"></span>
                                        ESP
                                    </li>
                                </ul>
                                <ul class="marcador3">
                                    <li>0</li>
                                    <li>0</li>
                                </ul>
                                <ul class="tabla-pais3 chi">
                                    <li>
                                        <span class="pais-p chi"></span>
                                        CHI
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="horaDialogo">
                            <h4>18/06 16:00</h4>
                            <h4>Río de Janeiro</h4>
                        </div>              
                    </div>  
                    <a class="close-reveal-modal">&#215;</a>
                </div>
                <div id="b4" class="reveal-modal small">
                    <p class="dialogoTit B">B</p>
                    <div class="grupo b" style="z-index: 1;">                                        
                        <div class="tabla-completa">                        
                            <div class="filaDialogo">
                                <ul class="tabla-pais3 aus">
                                    <li>
                                        <span class="pais-p aus"></span>
                                        AUS
                                    </li>
                                </ul>
                                <ul class="marcador3">
                                    <li>0</li>
                                    <li>0</li>
                                </ul>
                                <ul class="tabla-pais3 hol">
                                    <li>
                                        <span class="pais-p hol"></span>
                                        HOL
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="horaDialogo">
                            <h4>18/06 13:00</h4>
                            <h4>Porto Alegre</h4>
                        </div>              
                    </div>  
                    <a class="close-reveal-modal">&#215;</a>
                </div>
                <div id="b5" class="reveal-modal small">
                    <p class="dialogoTit B">B</p>
                    <div class="grupo b" style="z-index: 1;">                                        
                        <div class="tabla-completa">                        
                            <div class="filaDialogo">
                                <ul class="tabla-pais3 aus">
                                    <li>
                                        <span class="pais-p aus"></span>
                                        AUS
                                    </li>
                                </ul>
                                <ul class="marcador3">
                                    <li>0</li>
                                    <li>0</li>
                                </ul>
                                <ul class="tabla-pais3 esp">
                                    <li>
                                        <span class="pais-p esp"></span>
                                        ESP
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="horaDialogo">
                            <h4>23/06 13:00</h4>
                            <h4>Curitiba</h4>
                        </div>              
                    </div>  
                    <a class="close-reveal-modal">&#215;</a>
                </div>
                <div id="b6" class="reveal-modal small">
                    <p class="dialogoTit B">B</p>
                    <div class="grupo b" style="z-index: 1;">                                        
                        <div class="tabla-completa">                        
                            <div class="filaDialogo">
                                <ul class="tabla-pais3 hol">
                                    <li>
                                        <span class="pais-p hol"></span>
                                        HOL
                                    </li>
                                </ul>
                                <ul class="marcador3">
                                    <li>0</li>
                                    <li>0</li>
                                </ul>
                                <ul class="tabla-pais3 chi">
                                    <li>
                                        <span class="pais-p chi"></span>
                                        CHI
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="horaDialogo">
                            <h4>23/06 13:00</h4>
                            <h4>Sao Paulo</h4>
                        </div>              
                    </div>  
                    <a class="close-reveal-modal">&#215;</a>
                </div>

                <!----------------- POPUPS GRUPO C -------------------------->
                <div id="c1" class="reveal-modal small">
                    <p class="dialogoTit C">C</p>
                    <div class="grupo c" style="z-index: 1;">                                        
                        <div class="tabla-completa">                        
                            <div class="filaDialogo">
                                <ul class="tabla-pais3 col">
                                    <li>
                                        <span class="pais-p col"></span>
                                        COL
                                    </li>
                                </ul>
                                <ul class="marcador3">
                                    <li>0</li>
                                    <li>0</li>
                                </ul>
                                <ul class="tabla-pais3 gre">
                                    <li>
                                        <span class="pais-p gre"></span>
                                        GRE
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="horaDialogo">
                            <h4>14/06 13:00</h4>
                            <h4>Belo Horizonte</h4>
                        </div>              
                    </div>  
                    <a class="close-reveal-modal">&#215;</a>
                </div>
                <div id="c2" class="reveal-modal small">
                    <p class="dialogoTit C">C</p>
                    <div class="grupo c" style="z-index: 1;">                                        
                        <div class="tabla-completa">                        
                            <div class="filaDialogo">
                                <ul class="tabla-pais3 cdm">
                                    <li>
                                        <span class="pais-p cdm"></span>
                                        CDM
                                    </li>
                                </ul>
                                <ul class="marcador3">
                                    <li>0</li>
                                    <li>0</li>
                                </ul>
                                <ul class="tabla-pais3 jap">
                                    <li>
                                        <span class="pais-p jap"></span>
                                        JAP
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="horaDialogo">
                            <h4>14/06 22:00</h4>
                            <h4>Recife</h4>
                        </div>              
                    </div>  
                    <a class="close-reveal-modal">&#215;</a>
                </div>
                <div id="c3" class="reveal-modal small">
                    <p class="dialogoTit C">C</p>
                    <div class="grupo c" style="z-index: 1;">                                        
                        <div class="tabla-completa">                        
                            <div class="filaDialogo">
                                <ul class="tabla-pais3 col">
                                    <li>
                                        <span class="pais-p col"></span>
                                        COL
                                    </li>
                                </ul>
                                <ul class="marcador3">
                                    <li>0</li>
                                    <li>0</li>
                                </ul>
                                <ul class="tabla-pais3 cdm">
                                    <li>
                                        <span class="pais-p cdm"></span>
                                        CDM
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="horaDialogo">
                            <h4>19/06 13:00</h4>
                            <h4>Brasilia</h4>
                        </div>              
                    </div>  
                    <a class="close-reveal-modal">&#215;</a>
                </div>
                <div id="c4" class="reveal-modal small">
                    <p class="dialogoTit C">C</p>
                    <div class="grupo c" style="z-index: 1;">                                        
                        <div class="tabla-completa">                        
                            <div class="filaDialogo">
                                <ul class="tabla-pais3 jap">
                                    <li>
                                        <span class="pais-p jap"></span>
                                        JAP
                                    </li>
                                </ul>
                                <ul class="marcador3">
                                    <li>0</li>
                                    <li>0</li>
                                </ul>
                                <ul class="tabla-pais3 gre">
                                    <li>
                                        <span class="pais-p gre"></span>
                                        GRE
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="horaDialogo">
                            <h4>19/06 19:00</h4>
                            <h4>Natal</h4>
                        </div>              
                    </div>  
                    <a class="close-reveal-modal">&#215;</a>
                </div>
                <div id="c5" class="reveal-modal small">
                    <p class="dialogoTit C">C</p>
                    <div class="grupo c" style="z-index: 1;">                                        
                        <div class="tabla-completa">                        
                            <div class="filaDialogo">
                                <ul class="tabla-pais3 jap">
                                    <li>
                                        <span class="pais-p jap"></span>
                                        JAP
                                    </li>
                                </ul>
                                <ul class="marcador3">
                                    <li>0</li>
                                    <li>0</li>
                                </ul>
                                <ul class="tabla-pais3 col">
                                    <li>
                                        <span class="pais-p col"></span>
                                        COL
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="horaDialogo">
                            <h4>24/06 16:00</h4>
                            <h4>Cuiabá</h4>
                        </div>              
                    </div>  
                    <a class="close-reveal-modal">&#215;</a>
                </div>
                <div id="c6" class="reveal-modal small">
                    <p class="dialogoTit C">C</p>
                    <div class="grupo c" style="z-index: 1;">                                        
                        <div class="tabla-completa">                        
                            <div class="filaDialogo">
                                <ul class="tabla-pais3 gre">
                                    <li>
                                        <span class="pais-p gre"></span>
                                        GRE
                                    </li>
                                </ul>
                                <ul class="marcador3">
                                    <li>0</li>
                                    <li>0</li>
                                </ul>
                                <ul class="tabla-pais3 cdm">
                                    <li>
                                        <span class="pais-p cdm"></span>
                                        CDM
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="horaDialogo">
                            <h4>24/06 17:00</h4>
                            <h4>Fortaleza</h4>
                        </div>              
                    </div>  
                    <a class="close-reveal-modal">&#215;</a>
                </div>

                <!----------------- POPUPS GRUPO D -------------------------->
                <div id="d1" class="reveal-modal small">
                    <p class="dialogoTit D">D</p>
                    <div class="grupo d" style="z-index: 1;">                                        
                        <div class="tabla-completa">                        
                            <div class="filaDialogo">
                                <ul class="tabla-pais3 uru">
                                    <li>
                                        <span class="pais-p uru"></span>
                                        URU
                                    </li>
                                </ul>
                                <ul class="marcador3">
                                    <li>0</li>
                                    <li>0</li>
                                </ul>
                                <ul class="tabla-pais3 crc">
                                    <li>
                                        <span class="pais-p crc"></span>
                                        crc
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="horaDialogo">
                            <h4>14/06 16:00</h4>
                            <h4>Fortaleza</h4>
                        </div>              
                    </div>  
                    <a class="close-reveal-modal">&#215;</a>
                </div>
                <div id="d2" class="reveal-modal small">
                    <p class="dialogoTit D">D</p>
                    <div class="grupo d" style="z-index: 1;">                                        
                        <div class="tabla-completa">                        
                            <div class="filaDialogo">
                                <ul class="tabla-pais3 ing">
                                    <li>
                                        <span class="pais-p ing"></span>
                                        ING
                                    </li>
                                </ul>
                                <ul class="marcador3">
                                    <li>0</li>
                                    <li>0</li>
                                </ul>
                                <ul class="tabla-pais3 ita">
                                    <li>
                                        <span class="pais-p ita"></span>
                                        ITA
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="horaDialogo">
                            <h4>14/06 18:00</h4>
                            <h4>Manaos</h4>
                        </div>              
                    </div>  
                    <a class="close-reveal-modal">&#215;</a>
                </div>
                <div id="d3" class="reveal-modal small">
                    <p class="dialogoTit D">D</p>
                    <div class="grupo d" style="z-index: 1;">                                        
                        <div class="tabla-completa">                        
                            <div class="filaDialogo">
                                <ul class="tabla-pais3 uru">
                                    <li>
                                        <span class="pais-p uru"></span>
                                        URU
                                    </li>
                                </ul>
                                <ul class="marcador3">
                                    <li>0</li>
                                    <li>0</li>
                                </ul>
                                <ul class="tabla-pais3 ing">
                                    <li>
                                        <span class="pais-p ing"></span>
                                        ING
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="horaDialogo">
                            <h4>19/06 16:00</h4>
                            <h4>Sao Paulo</h4>
                        </div>              
                    </div>  
                    <a class="close-reveal-modal">&#215;</a>
                </div>
                <div id="d4" class="reveal-modal small">
                    <p class="dialogoTit D">D</p>
                    <div class="grupo d" style="z-index: 1;">                                        
                        <div class="tabla-completa">                        
                            <div class="filaDialogo">
                                <ul class="tabla-pais3 ita">
                                    <li>
                                        <span class="pais-p ita"></span>
                                        ITA
                                    </li>
                                </ul>
                                <ul class="marcador3">
                                    <li>0</li>
                                    <li>0</li>
                                </ul>
                                <ul class="tabla-pais3 crc">
                                    <li>
                                        <span class="pais-p crc"></span>
                                        crc
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="horaDialogo">
                            <h4>20/06 13:00</h4>
                            <h4>Recife</h4>
                        </div>              
                    </div>  
                    <a class="close-reveal-modal">&#215;</a>
                </div>
                <div id="d5" class="reveal-modal small">
                    <p class="dialogoTit D">D</p>
                    <div class="grupo d" style="z-index: 1;">                                        
                        <div class="tabla-completa">                        
                            <div class="filaDialogo">
                                <ul class="tabla-pais3 ita">
                                    <li>
                                        <span class="pais-p ita"></span>
                                        ITA
                                    </li>
                                </ul>
                                <ul class="marcador3">
                                    <li>0</li>
                                    <li>0</li>
                                </ul>
                                <ul class="tabla-pais3 uru">
                                    <li>
                                        <span class="pais-p uru"></span>
                                        URU
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="horaDialogo">
                            <h4>24/06 13:00</h4>
                            <h4>Natal</h4>
                        </div>              
                    </div>  
                    <a class="close-reveal-modal">&#215;</a>
                </div>
                <div id="d6" class="reveal-modal small">
                    <p class="dialogoTit D">D</p>
                    <div class="grupo d" style="z-index: 1;">                                        
                        <div class="tabla-completa">                        
                            <div class="filaDialogo">
                                <ul class="tabla-pais3 crc">
                                    <li>
                                        <span class="pais-p crc"></span>
                                        crc
                                    </li>
                                </ul>
                                <ul class="marcador3">
                                    <li>0</li>
                                    <li>0</li>
                                </ul>
                                <ul class="tabla-pais3 ing">
                                    <li>
                                        <span class="pais-p ing"></span>
                                        ING
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="horaDialogo">
                            <h4>24/06 13:00</h4>
                            <h4>Belo Horizonte</h4>
                        </div>              
                    </div>  
                    <a class="close-reveal-modal">&#215;</a>
                </div>


                <!----------------- POPUPS GRUPO E -------------------------->
                <div id="e1" class="reveal-modal small">
                    <p class="dialogoTit E">E</p>
                    <div class="grupo e" style="z-index: 1;">                                        
                        <div class="tabla-completa">                        
                            <div class="filaDialogo">
                                <ul class="tabla-pais3 sui">
                                    <li>
                                        <span class="pais-p sui"></span>
                                        SUI
                                    </li>
                                </ul>
                                <ul class="marcador3">
                                    <li>0</li>
                                    <li>0</li>
                                </ul>
                                <ul class="tabla-pais3 ecu">
                                    <li>
                                        <span class="pais-p ecu"></span>
                                        ECU
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="horaDialogo">
                            <h4>15/06 13:00</h4>
                            <h4>Brasilia</h4>
                        </div>              
                    </div>  
                    <a class="close-reveal-modal">&#215;</a>
                </div>
                <div id="e2" class="reveal-modal small">
                    <p class="dialogoTit E">E</p>
                    <div class="grupo e" style="z-index: 1;">                                        
                        <div class="tabla-completa">                        
                            <div class="filaDialogo">
                                <ul class="tabla-pais3 fra">
                                    <li>
                                        <span class="pais-p fra"></span>
                                        FRA
                                    </li>
                                </ul>
                                <ul class="marcador3">
                                    <li>0</li>
                                    <li>0</li>
                                </ul>
                                <ul class="tabla-pais3 hon">
                                    <li>
                                        <span class="pais-p hon"></span>
                                        HON
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="horaDialogo">
                            <h4>15/06 16:00</h4>
                            <h4>Porto Alegre</h4>
                        </div>              
                    </div>  
                    <a class="close-reveal-modal">&#215;</a>
                </div>
                <div id="e3" class="reveal-modal small">
                    <p class="dialogoTit E">E</p>
                    <div class="grupo e" style="z-index: 1;">                                        
                        <div class="tabla-completa">                        
                            <div class="filaDialogo">
                                <ul class="tabla-pais3 sui">
                                    <li>
                                        <span class="pais-p sui"></span>
                                        SUI
                                    </li>
                                </ul>
                                <ul class="marcador3">
                                    <li>0</li>
                                    <li>0</li>
                                </ul>
                                <ul class="tabla-pais3 fra">
                                    <li>
                                        <span class="pais-p fra"></span>
                                        FRA
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="horaDialogo">
                            <h4>20/06 16:00</h4>
                            <h4>Salvador</h4>
                        </div>              
                    </div>  
                    <a class="close-reveal-modal">&#215;</a>
                </div>
                <div id="e4" class="reveal-modal small">
                    <p class="dialogoTit E">E</p>
                    <div class="grupo e" style="z-index: 1;">                                        
                        <div class="tabla-completa">                        
                            <div class="filaDialogo">
                                <ul class="tabla-pais3 hon">
                                    <li>
                                        <span class="pais-p hon"></span>
                                        HON
                                    </li>
                                </ul>
                                <ul class="marcador3">
                                    <li>0</li>
                                    <li>0</li>
                                </ul>
                                <ul class="tabla-pais3 ecu">
                                    <li>
                                        <span class="pais-p ecu"></span>
                                        ECU
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="horaDialogo">
                            <h4>20/06 19:00</h4>
                            <h4>Curitiba</h4>
                        </div>              
                    </div>  
                    <a class="close-reveal-modal">&#215;</a>
                </div>
                <div id="e5" class="reveal-modal small">
                    <p class="dialogoTit E">E</p>
                    <div class="grupo e" style="z-index: 1;">                                        
                        <div class="tabla-completa">                        
                            <div class="filaDialogo">
                                <ul class="tabla-pais3 hon">
                                    <li>
                                        <span class="pais-p hon"></span>
                                        HON
                                    </li>
                                </ul>
                                <ul class="marcador3">
                                    <li>0</li>
                                    <li>0</li>
                                </ul>
                                <ul class="tabla-pais3 sui">
                                    <li>
                                        <span class="pais-p sui"></span>
                                        SUI
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="horaDialogo">
                            <h4>25/06 16:00</h4>
                            <h4>Manaos</h4>
                        </div>              
                    </div>  
                    <a class="close-reveal-modal">&#215;</a>
                </div>
                <div id="e6" class="reveal-modal small">
                    <p class="dialogoTit E">E</p>
                    <div class="grupo e" style="z-index: 1;">                                        
                        <div class="tabla-completa">                        
                            <div class="filaDialogo">
                                <ul class="tabla-pais3 ecu">
                                    <li>
                                        <span class="pais-p ecu"></span>
                                        ECU
                                    </li>
                                </ul>
                                <ul class="marcador3">
                                    <li>0</li>
                                    <li>0</li>
                                </ul>
                                <ul class="tabla-pais3 fra">
                                    <li>
                                        <span class="pais-p fra"></span>
                                        FRA
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="horaDialogo">
                            <h4>25/06 17:00</h4>
                            <h4>Río de Janeiro</h4>
                        </div>              
                    </div>  
                    <a class="close-reveal-modal">&#215;</a>
                </div>

                <!----------------- POPUPS GRUPO F -------------------------->
                <div id="f1" class="reveal-modal small">
                    <p class="dialogoTit F">F</p>
                    <div class="grupo f" style="z-index: 1;">                                        
                        <div class="tabla-completa">                        
                            <div class="filaDialogo">
                                <ul class="tabla-pais3 arg">
                                    <li>
                                        <span class="pais-p arg"></span>
                                        ARG
                                    </li>
                                </ul>
                                <ul class="marcador3">
                                    <li>0</li>
                                    <li>0</li>
                                </ul>
                                <ul class="tabla-pais3 bos">
                                    <li>
                                        <span class="pais-p bos"></span>
                                        BOS
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="horaDialogo">
                            <h4>15/06 19:00</h4>
                            <h4>Río de Janeiro</h4>
                        </div>              
                    </div>  
                    <a class="close-reveal-modal">&#215;</a>
                </div>
                <div id="f2" class="reveal-modal small">
                    <p class="dialogoTit F">F</p>
                    <div class="grupo f" style="z-index: 1;">                                        
                        <div class="tabla-completa">                        
                            <div class="filaDialogo">
                                <ul class="tabla-pais3 irn">
                                    <li>
                                        <span class="pais-p irn"></span>
                                        IRN
                                    </li>
                                </ul>
                                <ul class="marcador3">
                                    <li>0</li>
                                    <li>0</li>
                                </ul>
                                <ul class="tabla-pais3 nig">
                                    <li>
                                        <span class="pais-p nig"></span>
                                        NIG
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="horaDialogo">
                            <h4>16/06 16:00</h4>
                            <h4>Curitiba</h4>
                        </div>              
                    </div>  
                    <a class="close-reveal-modal">&#215;</a>
                </div>
                <div id="f3" class="reveal-modal small">
                    <p class="dialogoTit F">F</p>
                    <div class="grupo f" style="z-index: 1;">                                        
                        <div class="tabla-completa">                        
                            <div class="filaDialogo">
                                <ul class="tabla-pais3 arg">
                                    <li>
                                        <span class="pais-p arg"></span>
                                        ARG
                                    </li>
                                </ul>
                                <ul class="marcador3">
                                    <li>0</li>
                                    <li>0</li>
                                </ul>
                                <ul class="tabla-pais3 irn">
                                    <li>
                                        <span class="pais-p irn"></span>
                                        IRN
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="horaDialogo">
                            <h4>21/06 13:00</h4>
                            <h4>Belo Horizonte</h4>
                        </div>              
                    </div>  
                    <a class="close-reveal-modal">&#215;</a>
                </div>
                <div id="f4" class="reveal-modal small">
                    <p class="dialogoTit F">F</p>
                    <div class="grupo f" style="z-index: 1;">                                        
                        <div class="tabla-completa">                        
                            <div class="filaDialogo">
                                <ul class="tabla-pais3 nig">
                                    <li>
                                        <span class="pais-p nig"></span>
                                        NIG
                                    </li>
                                </ul>
                                <ul class="marcador3">
                                    <li>0</li>
                                    <li>0</li>
                                </ul>
                                <ul class="tabla-pais3 bos">
                                    <li>
                                        <span class="pais-p bos"></span>
                                        BOS
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="horaDialogo">
                            <h4>21/06 18:00</h4>
                            <h4>Cuiabá</h4>
                        </div>              
                    </div>  
                    <a class="close-reveal-modal">&#215;</a>
                </div>
                <div id="f5" class="reveal-modal small">
                    <p class="dialogoTit F">F</p>
                    <div class="grupo f" style="z-index: 1;">                                        
                        <div class="tabla-completa">                        
                            <div class="filaDialogo">
                                <ul class="tabla-pais3 nig">
                                    <li>
                                        <span class="pais-p nig"></span>
                                        NIG
                                    </li>
                                </ul>
                                <ul class="marcador3">
                                    <li>0</li>
                                    <li>0</li>
                                </ul>
                                <ul class="tabla-pais3 arg">
                                    <li>
                                        <span class="pais-p arg"></span>
                                        ARG
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="horaDialogo">
                            <h4>25/06 13:00</h4>
                            <h4>Porto Alegre</h4>
                        </div>              
                    </div>  
                    <a class="close-reveal-modal">&#215;</a>
                </div>
                <div id="f6" class="reveal-modal small">
                    <p class="dialogoTit F">F</p>
                    <div class="grupo f" style="z-index: 1;">                                        
                        <div class="tabla-completa">                        
                            <div class="filaDialogo">
                                <ul class="tabla-pais3 bos">
                                    <li>
                                        <span class="pais-p bos"></span>
                                        BOS
                                    </li>
                                </ul>
                                <ul class="marcador3">
                                    <li>0</li>
                                    <li>0</li>
                                </ul>
                                <ul class="tabla-pais3 irn">
                                    <li>
                                        <span class="pais-p irn"></span>
                                        IRN
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="horaDialogo">
                            <h4>25/06 13:00</h4>
                            <h4>Salvador</h4>
                        </div>              
                    </div>  
                    <a class="close-reveal-modal">&#215;</a>
                </div>


                <!----------------- POPUPS GRUPO G -------------------------->
                <div id="g1" class="reveal-modal small">
                    <p class="dialogoTit G">G</p>
                    <div class="grupo g" style="z-index: 1;">                                        
                        <div class="tabla-completa">                        
                            <div class="filaDialogo">
                                <ul class="tabla-pais3 ale">
                                    <li>
                                        <span class="pais-p ale"></span>
                                        ALE
                                    </li>
                                </ul>
                                <ul class="marcador3">
                                    <li>0</li>
                                    <li>0</li>
                                </ul>
                                <ul class="tabla-pais3 por">
                                    <li>
                                        <span class="pais-p por"></span>
                                        POR
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="horaDialogo">
                            <h4>16/06 13:00</h4>
                            <h4>Salvador</h4>
                        </div>              
                    </div>  
                    <a class="close-reveal-modal">&#215;</a>
                </div>
                <div id="g2" class="reveal-modal small">
                    <p class="dialogoTit G">G</p>
                    <div class="grupo g" style="z-index: 1;">                                        
                        <div class="tabla-completa">                        
                            <div class="filaDialogo">
                                <ul class="tabla-pais3 gha">
                                    <li>
                                        <span class="pais-p gha"></span>
                                        GHA
                                    </li>
                                </ul>
                                <ul class="marcador3">
                                    <li>0</li>
                                    <li>0</li>
                                </ul>
                                <ul class="tabla-pais3 eua">
                                    <li>
                                        <span class="pais-p eua"></span>
                                        EUA
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="horaDialogo">
                            <h4>16/06 19:00</h4>
                            <h4>Natal</h4>
                        </div>              
                    </div>  
                    <a class="close-reveal-modal">&#215;</a>
                </div>
                <div id="g3" class="reveal-modal small">
                    <p class="dialogoTit G">G</p>
                    <div class="grupo g" style="z-index: 1;">                                        
                        <div class="tabla-completa">                        
                            <div class="filaDialogo">
                                <ul class="tabla-pais3 ale">
                                    <li>
                                        <span class="pais-p ale"></span>
                                        ALE
                                    </li>
                                </ul>
                                <ul class="marcador3">
                                    <li>0</li>
                                    <li>0</li>
                                </ul>
                                <ul class="tabla-pais3 gha">
                                    <li>
                                        <span class="pais-p gha"></span>
                                        GHA
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="horaDialogo">
                            <h4>21/06 16:00</h4>
                            <h4>Fortaleza</h4>
                        </div>              
                    </div>  
                    <a class="close-reveal-modal">&#215;</a>
                </div>
                <div id="g4" class="reveal-modal small">
                    <p class="dialogoTit G">G</p>
                    <div class="grupo g" style="z-index: 1;">                                        
                        <div class="tabla-completa">                        
                            <div class="filaDialogo">
                                <ul class="tabla-pais3 eua">
                                    <li>
                                        <span class="pais-p eua"></span>
                                        EUA
                                    </li>
                                </ul>
                                <ul class="marcador3">
                                    <li>0</li>
                                    <li>0</li>
                                </ul>
                                <ul class="tabla-pais3 por">
                                    <li>
                                        <span class="pais-p por"></span>
                                        POR
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="horaDialogo">
                            <h4>22/06 18:00</h4>
                            <h4>Manaos</h4>
                        </div>              
                    </div>  
                    <a class="close-reveal-modal">&#215;</a>
                </div>
                <div id="g5" class="reveal-modal small">
                    <p class="dialogoTit G">G</p>
                    <div class="grupo g" style="z-index: 1;">                                        
                        <div class="tabla-completa">                        
                            <div class="filaDialogo">
                                <ul class="tabla-pais3 eua">
                                    <li>
                                        <span class="pais-p eua"></span>
                                        EUA
                                    </li>
                                </ul>
                                <ul class="marcador3">
                                    <li>0</li>
                                    <li>0</li>
                                </ul>
                                <ul class="tabla-pais3 ale">
                                    <li>
                                        <span class="pais-p ale"></span>
                                        ALE
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="horaDialogo">
                            <h4>26/06 13:00</h4>
                            <h4>Recife</h4>
                        </div>              
                    </div>  
                    <a class="close-reveal-modal">&#215;</a>
                </div>
                <div id="g6" class="reveal-modal small">
                    <p class="dialogoTit G">G</p>
                    <div class="grupo g" style="z-index: 1;">                                        
                        <div class="tabla-completa">                        
                            <div class="filaDialogo">
                                <ul class="tabla-pais3 por">
                                    <li>
                                        <span class="pais-p por"></span>
                                        POR
                                    </li>
                                </ul>
                                <ul class="marcador3">
                                    <li>0</li>
                                    <li>0</li>
                                </ul>
                                <ul class="tabla-pais3 gha">
                                    <li>
                                        <span class="pais-p gha"></span>
                                        GHA
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="horaDialogo">
                            <h4>26/06 13:00</h4>
                            <h4>Brasilia</h4>
                        </div>              
                    </div>  
                    <a class="close-reveal-modal">&#215;</a>
                </div>

                <!----------------- POPUPS GRUPO h -------------------------->
                <div id="h1" class="reveal-modal small">
                    <p class="dialogoTit H">H</p>
                    <div class="grupo h" style="z-index: 1;">                                        
                        <div class="tabla-completa">                        
                            <div class="filaDialogo">
                                <ul class="tabla-pais3 bel">
                                    <li>
                                        <span class="pais-p bel"></span>
                                        BEL
                                    </li>
                                </ul>
                                <ul class="marcador3">
                                    <li>0</li>
                                    <li>0</li>
                                </ul>
                                <ul class="tabla-pais3 agl">
                                    <li>
                                        <span class="pais-p agl"></span>
                                        AGL
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="horaDialogo">
                            <h4>17/06 13:00</h4>
                            <h4>Belo Horizonte</h4>
                        </div>              
                    </div>  
                    <a class="close-reveal-modal">&#215;</a>
                </div>
                <div id="h2" class="reveal-modal small">
                    <p class="dialogoTit H">H</p>
                    <div class="grupo h" style="z-index: 1;">                                        
                        <div class="tabla-completa">                        
                            <div class="filaDialogo">
                                <ul class="tabla-pais3 rus">
                                    <li>
                                        <span class="pais-p rus"></span>
                                        RUS
                                    </li>
                                </ul>
                                <ul class="marcador3">
                                    <li>0</li>
                                    <li>0</li>
                                </ul>
                                <ul class="tabla-pais3 cor">
                                    <li>
                                        <span class="pais-p cor"></span>
                                        COR
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="horaDialogo">
                            <h4>17/06 18:00</h4>
                            <h4>Cuiabá</h4>
                        </div>              
                    </div>  
                    <a class="close-reveal-modal">&#215;</a>
                </div>
                <div id="h3" class="reveal-modal small">
                    <p class="dialogoTit H">H</p>
                    <div class="grupo h" style="z-index: 1;">                                        
                        <div class="tabla-completa">                        
                            <div class="filaDialogo">
                                <ul class="tabla-pais3 bel">
                                    <li>
                                        <span class="pais-p bel"></span>
                                        BEL
                                    </li>
                                </ul>
                                <ul class="marcador3">
                                    <li>0</li>
                                    <li>0</li>
                                </ul>
                                <ul class="tabla-pais3 rus">
                                    <li>
                                        <span class="pais-p rus"></span>
                                        RUS
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="horaDialogo">
                            <h4>28 de JUnio 12:00 - 13:00 </h4>
                            <h4>Río de Janeiro</h4>
                        </div>              
                    </div>  
                    <a class="close-reveal-modal">&#215;</a>
                </div>
                <div id="h4" class="reveal-modal small">
                    <p class="dialogoTit H">H</p>
                    <div class="grupo h" style="z-index: 1;">                                        
                        <div class="tabla-completa">                        
                            <div class="filaDialogo">
                                <ul class="tabla-pais3 cor">
                                    <li>
                                        <span class="pais-p cor"></span>
                                        COR
                                    </li>
                                </ul>
                                <ul class="marcador3">
                                    <li>0</li>
                                    <li>0</li>
                                </ul>
                                <ul class="tabla-pais3 agl">
                                    <li>
                                        <span class="pais-p agl"></span>
                                        AGL
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="horaDialogo">
                            <h4>22/06 16:00</h4>
                            <h4>Sao Paulo</h4>
                        </div>              
                    </div>  
                    <a class="close-reveal-modal">&#215;</a>
                </div>
                <div id="h5" class="reveal-modal small">
                    <p class="dialogoTit H">H</p>
                    <div class="grupo h" style="z-index: 1;">                                        
                        <div class="tabla-completa">                        
                            <div class="filaDialogo">
                                <ul class="tabla-pais3 cor">
                                    <li>
                                        <span class="pais-p cor"></span>
                                        COR
                                    </li>
                                </ul>
                                <ul class="marcador3">
                                    <li>0</li>
                                    <li>0</li>
                                </ul>
                                <ul class="tabla-pais3 bel">
                                    <li>
                                        <span class="pais-p bel"></span>
                                        BEL
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="horaDialogo">
                            <h4>26/06 17:00</h4>
                            <h4>Sao Paulo</h4>
                        </div>              
                    </div>  
                    <a class="close-reveal-modal">&#215;</a>
                </div>
                <div id="h6" class="reveal-modal small">
                    <p class="dialogoTit H">H</p>
                    <div class="grupo h" style="z-index: 1;">                                        
                        <div class="tabla-completa">                        
                            <div class="filaDialogo">
                                <ul class="tabla-pais3 agl">
                                    <li>
                                        <span class="pais-p agl"></span>
                                        AGL
                                    </li>
                                </ul>
                                <ul class="marcador3">
                                    <li>0</li>
                                    <li>0</li>
                                </ul>
                                <ul class="tabla-pais3 rus">
                                    <li>
                                        <span class="pais-p rus"></span>
                                        RUS
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="horaDialogo">
                            <h4>26/06 17:00</h4>
                            <h4>Curitiba</h4>
                        </div>              
                    </div>  
                    <a class="close-reveal-modal">&#215;</a>
                </div>

                <section id="accordion">

                    <div class="modulo grupoa">
                        <div class="ac-container">
                            <label>
                                <div class="tabla-completa">                        
                                    <div class="fila">
                                        <ul class="tabla-pais">
                                            <li><span class="pais-p bra"></span>BRA</li>
                                        </ul>
                                        <ul class="tabla-pais">
                                            <li><span class="pais-p cro"></span>CRO</li>
                                        </ul>
                                        <ul class="tabla-pais">
                                            <li><span class="pais-p mex"></span>MEX</li>
                                        </ul>
                                        <ul class="tabla-pais">
                                            <li><span class="pais-p cam"></span>CAM</li>
                                        </ul>
                                    </div>
                                </div>
                            </label>
                        </div>
                    </div>
                    <div class="todos-los-equipos">
                        <div class="grupo a">  
                            <div class="tabla-completa">                  
                                <div class="fila">
                                    <a href="#a1" class="iconoFechas" data-reveal-id="a1" data-animation="fade">
                                        <ul class="tabla-pais2">
                                            <li>BRA</li>
                                        </ul>
                                        <ul class="marcador">
                                            <li>0</li>
                                            <li>0</li>
                                        </ul>
                                        <ul class="tabla-pais2">
                                            <li>CRO</li>
                                        </ul>
                                    </a>
                                </div>
                            </div>
                            <div class="tabla-completa">                        
                                <div class="fila color-a"><a href="#a2" class="iconoFechas" data-reveal-id="a2" data-animation="fade">
                                        <ul class="tabla-pais2">
                                            <li>MEX</li>
                                        </ul>
                                        <ul class="marcador">
                                            <li>0</li>
                                            <li>0</li>
                                        </ul>
                                        <ul class="tabla-pais2">
                                            <li>CAM</li>
                                        </ul>
                                    </a>
                                </div>
                            </div>

                            <div class="tabla-completa">                        
                                <div class="fila"><a href="#a3" class="iconoFechas" data-reveal-id="a3" data-animation="fade">
                                        <ul class="tabla-pais2">
                                            <li>BRA</li>
                                        </ul>
                                        <ul class="marcador">
                                            <li>0</li>
                                            <li>0</li>
                                        </ul>
                                        <ul class="tabla-pais2">
                                            <li>MEX</li>
                                        </ul>
                                    </a>
                                </div>
                            </div>

                            <div class="tabla-completa">                        
                                <div class="fila color-a"><a href="#a4" class="iconoFechas" data-reveal-id="a4" data-animation="fade">
                                        <ul class="tabla-pais2">
                                            <li>CAM</li>
                                        </ul>
                                        <ul class="marcador">
                                            <li>0</li>
                                            <li>0</li>
                                        </ul>
                                        <ul class="tabla-pais2">
                                            <li>CRO</li>
                                        </ul>
                                    </a>
                                </div>
                            </div>

                            <div class="tabla-completa">                        
                                <div class="fila"><a href="#a5" class="iconoFechas" data-reveal-id="a5" data-animation="fade">
                                        <ul class="tabla-pais2">
                                            <li>CAM</li>
                                        </ul>
                                        <ul class="marcador">
                                            <li>0</li>
                                            <li>0</li>
                                        </ul>
                                        <ul class="tabla-pais2">
                                            <li>BRA</li>
                                        </ul>
                                    </a>
                                </div>
                            </div>

                            <div class="tabla-completa">                        
                                <div class="fila color-a"><a href="#a6" class="iconoFechas" data-reveal-id="a6" data-animation="fade">
                                        <ul class="tabla-pais2">
                                            <li>CRO</li>
                                        </ul>
                                        <ul class="marcador">
                                            <li>0</li>
                                            <li>0</li>
                                        </ul>
                                        <ul class="tabla-pais2">
                                            <li>MEX</li>
                                        </ul>
                                    </a>
                                </div>
                            </div>
                        </div>                                                                                        
                    </div>
                    <div class="modulo grupob">
                        <div class="ac-container">
                            <label>
                                <div class="tabla-completa">                        
                                    <div class="fila">
                                        <ul class="tabla-pais">
                                            <li><span class="pais-p esp"></span>ESP</li>
                                        </ul>
                                        <ul class="tabla-pais">
                                            <li><span class="pais-p hol"></span>HOL</li>
                                        </ul>
                                        <ul class="tabla-pais">
                                            <li><span class="pais-p chi"></span>CHI</li>
                                        </ul>
                                        <ul class="tabla-pais">
                                            <li><span class="pais-p aus"></span>AUS</li>
                                        </ul>
                                    </div>
                                </div>
                            </label>
                        </div>
                    </div>
                    <div class="todos-los-equipos">
                        <div class="grupo b" style="z-index: 1;">

                            <div class="tabla-completa">                        
                                <div class="fila"><a href="#b1" class="iconoFechas" data-reveal-id="b1" data-animation="fade">
                                        <ul class="tabla-pais2">
                                            <li>ESP</li>
                                        </ul>
                                        <ul class="marcador">
                                            <li>0</li>
                                            <li>0</li>
                                        </ul>
                                        <ul class="tabla-pais2">
                                            <li>HOL</li>
                                        </ul>
                                    </a>
                                </div>
                            </div>

                            <div class="tabla-completa">                        
                                <div class="fila color-b"><a href="#b2" class="iconoFechas" data-reveal-id="b2" data-animation="fade">
                                        <ul class="tabla-pais2">
                                            <li>CHI</li>
                                        </ul>
                                        <ul class="marcador">
                                            <li>0</li>
                                            <li>0</li>
                                        </ul>
                                        <ul class="tabla-pais2">
                                            <li>AUS</li>
                                        </ul>
                                    </a>
                                </div>
                            </div>

                            <div class="tabla-completa">                        
                                <div class="fila"><a href="#b3" class="iconoFechas" data-reveal-id="b3" data-animation="fade">
                                        <ul class="tabla-pais2">
                                            <li>ESP</li>
                                        </ul>
                                        <ul class="marcador">
                                            <li>0</li>
                                            <li>0</li>
                                        </ul>
                                        <ul class="tabla-pais2">
                                            <li>CHI</li>
                                        </ul>
                                    </a>
                                </div>
                            </div>

                            <div class="tabla-completa">                        
                                <div class="fila color-b"><a href="#b4" class="iconoFechas" data-reveal-id="b4" data-animation="fade">
                                        <ul class="tabla-pais2">
                                            <li>AUS</li>
                                        </ul>
                                        <ul class="marcador">
                                            <li>0</li>
                                            <li>0</li>
                                        </ul>
                                        <ul class="tabla-pais2">
                                            <li>HOL</li>
                                        </ul>
                                    </a>
                                </div>
                            </div>

                            <div class="tabla-completa">                        
                                <div class="fila"><a href="#b5" class="iconoFechas" data-reveal-id="b5" data-animation="fade">
                                        <ul class="tabla-pais2">
                                            <li>AUS</li>
                                        </ul>
                                        <ul class="marcador">
                                            <li>0</li>
                                            <li>0</li>
                                        </ul>
                                        <ul class="tabla-pais2">
                                            <li>ESP</li>
                                        </ul>
                                    </a>
                                </div>
                            </div>

                            <div class="tabla-completa">                        
                                <div class="fila color-b"><a href="#b6" class="iconoFechas" data-reveal-id="b6" data-animation="fade">
                                        <ul class="tabla-pais2">
                                            <li>HOL</li>
                                        </ul>
                                        <ul class="marcador">
                                            <li>0</li>
                                            <li>0</li>
                                        </ul>
                                        <ul class="tabla-pais2">
                                            <li>CHI</li>
                                        </ul>
                                    </a>
                                </div>
                            </div>
                        </div>                                                                    
                    </div>


                    <div class="modulo grupoc">
                        <div class="ac-container">
                            <label>
                                <div class="tabla-completa">                        
                                    <div class="fila">
                                        <ul class="tabla-pais">
                                            <li><span class="pais-p col"></span>COL</li>
                                        </ul>
                                        <ul class="tabla-pais">
                                            <li><span class="pais-p gre"></span>GRE</li>
                                        </ul>
                                        <ul class="tabla-pais">
                                            <li><span class="pais-p cdm"></span>CDM</li>
                                        </ul>
                                        <ul class="tabla-pais">
                                            <li><span class="pais-p jap"></span>JAP</li>
                                        </ul>
                                    </div>
                                </div>
                            </label>
                            </label>
                        </div>
                    </div>
                    <div class="todos-los-equipos">
                        <div class="grupo c" style="z-index: 1;">

                            <div class="tabla-completa">                        
                                <div class="fila"><a href="#c1" class="iconoFechas" data-reveal-id="c1" data-animation="fade">
                                        <ul class="tabla-pais2">
                                            <li>COL</li>
                                        </ul>
                                        <ul class="marcador">
                                            <li>0</li>
                                            <li>0</li>
                                        </ul>
                                        <ul class="tabla-pais2">
                                            <li>GRE</li>
                                        </ul>
                                    </a>
                                </div>
                            </div>

                            <div class="tabla-completa">                        
                                <div class="fila color-c"><a href="#c2" class="iconoFechas" data-reveal-id="c2" data-animation="fade">
                                        <ul class="tabla-pais2">
                                            <li>CDM</li>
                                        </ul>
                                        <ul class="marcador">
                                            <li>0</li>
                                            <li>0</li>
                                        </ul>
                                        <ul class="tabla-pais2">
                                            <li>JAP</li>
                                        </ul>
                                    </a>
                                </div>
                            </div>

                            <div class="tabla-completa">                        
                                <div class="fila"><a href="#c3" class="iconoFechas" data-reveal-id="c3" data-animation="fade">
                                        <ul class="tabla-pais2">
                                            <li>COL</li>
                                        </ul>
                                        <ul class="marcador">
                                            <li>0</li>
                                            <li>0</li>
                                        </ul>
                                        <ul class="tabla-pais2">
                                            <li>CDM</li>
                                        </ul>
                                    </a>
                                </div>
                            </div>

                            <div class="tabla-completa">                        
                                <div class="fila color-c"><a href="#c4" class="iconoFechas" data-reveal-id="c4" data-animation="fade">
                                        <ul class="tabla-pais2">
                                            <li>JAP</li>
                                        </ul>
                                        <ul class="marcador">
                                            <li>0</li>
                                            <li>0</li>
                                        </ul>
                                        <ul class="tabla-pais2">
                                            <li>GRE</li>
                                        </ul>
                                    </a>
                                </div>
                            </div>

                            <div class="tabla-completa">                        
                                <div class="fila"><a href="#c5" class="iconoFechas" data-reveal-id="c5" data-animation="fade">
                                        <ul class="tabla-pais2">
                                            <li>JAP</li>
                                        </ul>
                                        <ul class="marcador">
                                            <li>0</li>
                                            <li>0</li>
                                        </ul>
                                        <ul class="tabla-pais2">
                                            <li>COL</li>
                                        </ul>
                                    </a>
                                </div>
                            </div>

                            <div class="tabla-completa">                        
                                <div class="fila color-c"><a href="#c6" class="iconoFechas" data-reveal-id="c6" data-animation="fade">
                                        <ul class="tabla-pais2">
                                            <li>GRE</li>
                                        </ul>
                                        <ul class="marcador">
                                            <li>0</li>
                                            <li>0</li>
                                        </ul>
                                        <ul class="tabla-pais2">
                                            <li>CDM</li>
                                        </ul>
                                    </a>
                                </div>
                            </div>
                        </div>                                                                    
                    </div>


                    <div class="modulo grupod">
                        <div class="ac-container">
                            <label>
                                <div class="tabla-completa">                        
                                    <div class="fila">
                                        <ul class="tabla-pais">
                                            <li><span class="pais-p uru"></span>URU</li>
                                        </ul>
                                        <ul class="tabla-pais">
                                            <li><span class="pais-p cro"></span>CRC</li>
                                        </ul>
                                        <ul class="tabla-pais">
                                            <li><span class="pais-p ing"></span>ING</li>
                                        </ul>
                                        <ul class="tabla-pais">
                                            <li><span class="pais-p ita"></span>ITA</li>
                                        </ul>
                                    </div>
                                </div>
                            </label>
                            </label>
                        </div>
                    </div>
                    <div class="todos-los-equipos">
                        <div class="grupo d" style="z-index: 1;">

                            <div class="tabla-completa">                        
                                <div class="fila"><a href="#d1" class="iconoFechas" data-reveal-id="d1" data-animation="fade">
                                        <ul class="tabla-pais2">
                                            <li>URU</li>
                                        </ul>
                                        <ul class="marcador">
                                            <li>0</li>
                                            <li>0</li>
                                        </ul>
                                        <ul class="tabla-pais2">
                                            <li>CRC</li>
                                        </ul>
                                    </a>
                                </div>
                            </div>

                            <div class="tabla-completa">                        
                                <div class="fila color-d"><a href="#d2" class="iconoFechas" data-reveal-id="d2" data-animation="fade">
                                        <ul class="tabla-pais2">
                                            <li>ING</li>
                                        </ul>
                                        <ul class="marcador">
                                            <li>0</li>
                                            <li>0</li>
                                        </ul>
                                        <ul class="tabla-pais2">
                                            <li>ITA</li>
                                        </ul>
                                    </a>
                                </div>
                            </div>

                            <div class="tabla-completa">                        
                                <div class="fila"><a href="#d3" class="iconoFechas" data-reveal-id="d3" data-animation="fade">
                                        <ul class="tabla-pais2">
                                            <li>URU</li>
                                        </ul>
                                        <ul class="marcador">
                                            <li>0</li>
                                            <li>0</li>
                                        </ul>
                                        <ul class="tabla-pais2">
                                            <li>ING</li>
                                        </ul>
                                    </a>
                                </div>
                            </div>

                            <div class="tabla-completa">                        
                                <div class="fila color-d"><a href="#d4" class="iconoFechas" data-reveal-id="d4" data-animation="fade">
                                        <ul class="tabla-pais2">
                                            <li>ITA</li>
                                        </ul>
                                        <ul class="marcador">
                                            <li>0</li>
                                            <li>0</li>
                                        </ul>
                                        <ul class="tabla-pais2">
                                            <li>CRC</li>
                                        </ul>
                                    </a>
                                </div>
                            </div>

                            <div class="tabla-completa">                        
                                <div class="fila"><a href="#d5" class="iconoFechas" data-reveal-id="d5" data-animation="fade">
                                        <ul class="tabla-pais2">
                                            <li>ITA</li>
                                        </ul>
                                        <ul class="marcador">
                                            <li>0</li>
                                            <li>0</li>
                                        </ul>
                                        <ul class="tabla-pais2">
                                            <li>URU</li>
                                        </ul>
                                    </a>
                                </div>
                            </div>

                            <div class="tabla-completa">                        
                                <div class="fila color-d"><a href="#d6" class="iconoFechas" data-reveal-id="d6" data-animation="fade">
                                        <ul class="tabla-pais2">
                                            <li>CRC</li>
                                        </ul>
                                        <ul class="marcador">
                                            <li>0</li>
                                            <li>0</li>
                                        </ul>
                                        <ul class="tabla-pais2">
                                            <li>ING</li>
                                        </ul>
                                    </a>
                                </div>
                            </div>
                        </div>                                                                    
                    </div>


                    <div class="modulo grupoe">
                        <div class="ac-container">
                            <label>
                                <div class="tabla-completa">                        
                                    <div class="fila">
                                        <ul class="tabla-pais">
                                            <li><span class="pais-p sui"></span>SUI</li>
                                        </ul>
                                        <ul class="tabla-pais">
                                            <li><span class="pais-p ecu"></span>ECU</li>
                                        </ul>
                                        <ul class="tabla-pais">
                                            <li><span class="pais-p fra"></span>FRA</li>
                                        </ul>
                                        <ul class="tabla-pais">
                                            <li><span class="pais-p hon"></span>HON</li>
                                        </ul>
                                    </div>
                                </div>
                            </label>
                        </div>
                    </div>
                    <div class="todos-los-equipos">
                        <div class="grupo e" style="z-index: 1;">

                            <div class="tabla-completa">                        
                                <div class="fila"><a href="#e1" class="iconoFechas" data-reveal-id="e1" data-animation="fade">
                                        <ul class="tabla-pais2">
                                            <li>SUI</li>
                                        </ul>
                                        <ul class="marcador">
                                            <li>0</li>
                                            <li>0</li>
                                        </ul>
                                        <ul class="tabla-pais2">
                                            <li>ECU</li>
                                        </ul>
                                    </a>
                                </div>
                            </div>

                            <div class="tabla-completa">                        
                                <div class="fila color-e"><a href="#e2" class="iconoFechas" data-reveal-id="e2" data-animation="fade">
                                        <ul class="tabla-pais2">
                                            <li>FRA</li>
                                        </ul>
                                        <ul class="marcador">
                                            <li>0</li>
                                            <li>0</li>
                                        </ul>
                                        <ul class="tabla-pais2">
                                            <li>HON</li>
                                        </ul>
                                    </a>
                                </div>
                            </div>

                            <div class="tabla-completa">                        
                                <div class="fila"><a href="#e3" class="iconoFechas" data-reveal-id="e3" data-animation="fade">
                                        <ul class="tabla-pais2">
                                            <li>SUI</li>
                                        </ul>
                                        <ul class="marcador">
                                            <li>0</li>
                                            <li>0</li>
                                        </ul>
                                        <ul class="tabla-pais2">
                                            <li>FRA</li>
                                        </ul>
                                    </a>
                                </div>
                            </div>

                            <div class="tabla-completa">                        
                                <div class="fila color-e"><a href="#e4" class="iconoFechas" data-reveal-id="e4" data-animation="fade">
                                        <ul class="tabla-pais2">
                                            <li>HON</li>
                                        </ul>
                                        <ul class="marcador">
                                            <li>0</li>
                                            <li>0</li>
                                        </ul>
                                        <ul class="tabla-pais2">
                                            <li>ECU</li>
                                        </ul>
                                    </a>
                                </div>
                            </div>

                            <div class="tabla-completa">                        
                                <div class="fila"><a href="#e5" class="iconoFechas" data-reveal-id="e5" data-animation="fade">
                                        <ul class="tabla-pais2">
                                            <li>HON</li>
                                        </ul>
                                        <ul class="marcador">
                                            <li>0</li>
                                            <li>0</li>
                                        </ul>
                                        <ul class="tabla-pais2">
                                            <li>SUI</li>
                                        </ul>
                                    </a>
                                </div>
                            </div>

                            <div class="tabla-completa">                        
                                <div class="fila color-e"><a href="#e6" class="iconoFechas" data-reveal-id="e6" data-animation="fade">
                                        <ul class="tabla-pais2">
                                            <li>ECU</li>
                                        </ul>
                                        <ul class="marcador">
                                            <li>0</li>
                                            <li>0</li>
                                        </ul>
                                        <ul class="tabla-pais2">
                                            <li>FRA</li>
                                        </ul>
                                    </a>
                                </div>
                            </div>
                        </div>                                                                    
                    </div>




                    <div class="modulo grupof">
                        <div class="ac-container">
                            <label>
                                <div class="tabla-completa">                        
                                    <div class="fila">
                                        <ul class="tabla-pais">
                                            <li><span class="pais-p arg"></span>ARG</li>
                                        </ul>
                                        <ul class="tabla-pais">
                                            <li><span class="pais-p bos"></span>BOS</li>
                                        </ul>
                                        <ul class="tabla-pais">
                                            <li><span class="pais-p irn"></span>IRN</li>
                                        </ul>
                                        <ul class="tabla-pais">
                                            <li><span class="pais-p nig"></span>NIG</li>
                                        </ul>
                                    </div>
                                </div>
                            </label>
                        </div>
                    </div>
                    <div class="todos-los-equipos">
                        <div class="grupo f" style="z-index: 1;">

                            <div class="tabla-completa">                        
                                <div class="fila"><a href="#f1" class="iconoFechas" data-reveal-id="f1" data-animation="fade">
                                        <ul class="tabla-pais2">
                                            <li>ARG</li>
                                        </ul>
                                        <ul class="marcador">
                                            <li>0</li>
                                            <li>0</li>
                                        </ul>
                                        <ul class="tabla-pais2">
                                            <li>BOS</li>
                                        </ul>
                                    </a>
                                </div>
                            </div>

                            <div class="tabla-completa">                        
                                <div class="fila color-f"><a href="#f2" class="iconoFechas" data-reveal-id="f2" data-animation="fade">
                                        <ul class="tabla-pais2">
                                            <li>IRN</li>
                                        </ul>
                                        <ul class="marcador">
                                            <li>0</li>
                                            <li>0</li>
                                        </ul>
                                        <ul class="tabla-pais2">
                                            <li>NIG</li>
                                        </ul>
                                    </a>
                                </div>
                            </div>

                            <div class="tabla-completa">                        
                                <div class="fila"><a href="#f3" class="iconoFechas" data-reveal-id="f3" data-animation="fade">
                                        <ul class="tabla-pais2">
                                            <li>ARG</li>
                                        </ul>
                                        <ul class="marcador">
                                            <li>0</li>
                                            <li>0</li>
                                        </ul>
                                        <ul class="tabla-pais2">
                                            <li>IRN</li>
                                        </ul>
                                    </a>
                                </div>
                            </div>

                            <div class="tabla-completa">                        
                                <div class="fila color-f"><a href="#f4" class="iconoFechas" data-reveal-id="f4" data-animation="fade">
                                        <ul class="tabla-pais2">
                                            <li>NIG</li>
                                        </ul>
                                        <ul class="marcador">
                                            <li>0</li>
                                            <li>0</li>
                                        </ul>
                                        <ul class="tabla-pais2">
                                            <li>BOS</li>
                                        </ul>
                                    </a>
                                </div>
                            </div>

                            <div class="tabla-completa">                        
                                <div class="fila"><a href="#f5" class="iconoFechas" data-reveal-id="f5" data-animation="fade">
                                        <ul class="tabla-pais2">
                                            <li>NIG</li>
                                        </ul>
                                        <ul class="marcador">
                                            <li>0</li>
                                            <li>0</li>
                                        </ul>
                                        <ul class="tabla-pais2">
                                            <li>ARG</li>
                                        </ul>
                                    </a>
                                </div>
                            </div>

                            <div class="tabla-completa">                        
                                <div class="fila color-f"><a href="#f6" class="iconoFechas" data-reveal-id="f6" data-animation="fade">
                                        <ul class="tabla-pais2">
                                            <li>BOS</li>
                                        </ul>
                                        <ul class="marcador">
                                            <li>0</li>
                                            <li>0</li>
                                        </ul>
                                        <ul class="tabla-pais2">
                                            <li>IRN</li>
                                        </ul>
                                    </a>
                                </div>
                            </div>
                        </div>                                                                    
                    </div>



                    <div class="modulo grupog">
                        <div class="ac-container">
                            <label>
                                <div class="tabla-completa">                        
                                    <div class="fila">
                                        <ul class="tabla-pais">
                                            <li><span class="pais-p ale"></span>ALE</li>
                                        </ul>
                                        <ul class="tabla-pais">
                                            <li><span class="pais-p por"></span>POR</li>
                                        </ul>
                                        <ul class="tabla-pais">
                                            <li><span class="pais-p gha"></span>GHA</li>
                                        </ul>
                                        <ul class="tabla-pais">
                                            <li><span class="pais-p eua"></span>EUA</li>
                                        </ul>
                                    </div>
                                </div>
                            </label>
                        </div>
                    </div>
                    <div class="todos-los-equipos">
                        <div class="grupo g" style="z-index: 1;">

                            <div class="tabla-completa">                        
                                <div class="fila"><a href="#g1" class="iconoFechas" data-reveal-id="g1" data-animation="fade">
                                        <ul class="tabla-pais2">
                                            <li>ALE</li>
                                        </ul>
                                        <ul class="marcador">
                                            <li>0</li>
                                            <li>0</li>
                                        </ul>
                                        <ul class="tabla-pais2">
                                            <li>POR</li>
                                        </ul>
                                    </a>
                                </div>
                            </div>

                            <div class="tabla-completa">                        
                                <div class="fila color-g"><a href="#g2" class="iconoFechas" data-reveal-id="g2" data-animation="fade">
                                        <ul class="tabla-pais2">
                                            <li>GHA</li>
                                        </ul>
                                        <ul class="marcador">
                                            <li>0</li>
                                            <li>0</li>
                                        </ul>
                                        <ul class="tabla-pais2">
                                            <li>EUA</li>
                                        </ul>
                                    </a>
                                </div>
                            </div>

                            <div class="tabla-completa">                        
                                <div class="fila"><a href="#g3" class="iconoFechas" data-reveal-id="g3" data-animation="fade">
                                        <ul class="tabla-pais2">
                                            <li>ALE</li>
                                        </ul>
                                        <ul class="marcador">
                                            <li>0</li>
                                            <li>0</li>
                                        </ul>
                                        <ul class="tabla-pais2">
                                            <li>GHA</li>
                                        </ul>
                                    </a>
                                </div>
                            </div>

                            <div class="tabla-completa">                        
                                <div class="fila color-g"><a href="#g4" class="iconoFechas" data-reveal-id="g4" data-animation="fade">
                                        <ul class="tabla-pais2">
                                            <li>EUA</li>
                                        </ul>
                                        <ul class="marcador">
                                            <li>0</li>
                                            <li>0</li>
                                        </ul>
                                        <ul class="tabla-pais2">
                                            <li>POR</li>
                                        </ul>
                                    </a>
                                </div>
                            </div>

                            <div class="tabla-completa">                        
                                <div class="fila"><a href="#g5" class="iconoFechas" data-reveal-id="g5" data-animation="fade">
                                        <ul class="tabla-pais2">
                                            <li>EUA</li>
                                        </ul>
                                        <ul class="marcador">
                                            <li>0</li>
                                            <li>0</li>
                                        </ul>
                                        <ul class="tabla-pais2">
                                            <li>ALE</li>
                                        </ul>
                                    </a>
                                </div>
                            </div>

                            <div class="tabla-completa">                        
                                <div class="fila color-g"><a href="#g6" class="iconoFechas" data-reveal-id="g6" data-animation="fade">
                                        <ul class="tabla-pais2">
                                            <li>POR</li>
                                        </ul>
                                        <ul class="marcador">
                                            <li>0</li>
                                            <li>0</li>
                                        </ul>
                                        <ul class="tabla-pais2">
                                            <li>GHA</li>
                                        </ul>
                                    </a>
                                </div>
                            </div>
                        </div>                                                                    
                    </div>



                    <div class="modulo grupoh">
                        <div class="ac-container">
                            <label>
                                <div class="tabla-completa">                        
                                    <div class="fila">
                                        <ul class="tabla-pais">
                                            <li><span class="pais-p bel"></span>BEL</li>
                                        </ul>
                                        <ul class="tabla-pais">
                                            <li><span class="pais-p rus"></span>RUS</li>
                                        </ul>
                                        <ul class="tabla-pais">
                                            <li><span class="pais-p cor"></span>COR</li>
                                        </ul>
                                        <ul class="tabla-pais">
                                            <li><span class="pais-p agl"></span>AGL</li>
                                        </ul>
                                    </div>
                                </div>
                            </label>
                        </div>
                    </div>
                    <div class="todos-los-equipos">
                        <div class="grupo h" style="z-index: 1;">

                            <div class="tabla-completa">                        
                                <div class="fila"><a href="#h1" class="iconoFechas" data-reveal-id="h1" data-animation="fade">
                                        <ul class="tabla-pais2">
                                            <li>BEL</li>
                                        </ul>
                                        <ul class="marcador">
                                            <li>0</li>
                                            <li>0</li>
                                        </ul>
                                        <ul class="tabla-pais2">
                                            <li>AGL</li>
                                        </ul>
                                    </a>
                                </div>
                            </div>

                            <div class="tabla-completa">                        
                                <div class="fila color-h"><a href="#h2" class="iconoFechas" data-reveal-id="h2" data-animation="fade">
                                        <ul class="tabla-pais2">
                                            <li>RUS</li>
                                        </ul>
                                        <ul class="marcador">
                                            <li>0</li>
                                            <li>0</li>
                                        </ul>
                                        <ul class="tabla-pais2">
                                            <li>COR</li>
                                        </ul>
                                    </a>
                                </div>
                            </div>

                            <div class="tabla-completa">                        
                                <div class="fila"><a href="#h3" class="iconoFechas" data-reveal-id="h3" data-animation="fade">
                                        <ul class="tabla-pais2">
                                            <li>BEL</li>
                                        </ul>
                                        <ul class="marcador">
                                            <li>0</li>
                                            <li>0</li>
                                        </ul>
                                        <ul class="tabla-pais2">
                                            <li>RUS</li>
                                        </ul>
                                    </a>
                                </div>
                            </div>

                            <div class="tabla-completa">                        
                                <div class="fila color-h"><a href="#h4" class="iconoFechas" data-reveal-id="h4" data-animation="fade">
                                        <ul class="tabla-pais2">
                                            <li>COR</li>
                                        </ul>
                                        <ul class="marcador">
                                            <li>0</li>
                                            <li>0</li>
                                        </ul>
                                        <ul class="tabla-pais2">
                                            <li>AGL</li>
                                        </ul>
                                    </a>
                                </div>
                            </div>

                            <div class="tabla-completa">                        
                                <div class="fila"><a href="#h5" class="iconoFechas" data-reveal-id="h5" data-animation="fade">
                                        <ul class="tabla-pais2">
                                            <li>COR</li>
                                        </ul>
                                        <ul class="marcador">
                                            <li>0</li>
                                            <li>0</li>
                                        </ul>
                                        <ul class="tabla-pais2">
                                            <li>BEL</li>
                                        </ul>
                                    </a>
                                </div>
                            </div>

                            <div class="tabla-completa">                        
                                <div class="fila color-h"><a href="#h6" class="iconoFechas" data-reveal-id="h6" data-animation="fade">
                                        <ul class="tabla-pais2">
                                            <li>AGL</li>
                                        </ul>
                                        <ul class="marcador">
                                            <li>0</li>
                                            <li>0</li>
                                        </ul>
                                        <ul class="tabla-pais2">
                                            <li>RUS</li>
                                        </ul>
                                    </a>
                                </div>
                            </div>
                        </div>                                                                    
                    </div>
                </section>   
            </div>


            <?php print $this->footer(); ?>

            <div class="botonesInferiores">
                <a href="/mundial-brasil-2014/calendario">Calendario</a>
                <a href="posiciones">Posiciones</a>
            </div>

        </div>
        <?php print $this->menu(); ?>
    </div>

    <!-- jQuery -->
    <script src="/mundial-brasil-2014/js/jquery.min_1.js"></script>
    <script>window.jQuery || document.write('<script src="js/libs/jquery-1.7.min.js">\x3C/script>')</script>

    <!-- FlexSlider -->
    <script defer src="/mundial-brasil-2014/js/jsCalendario/jquery.flexslider.js"></script>

    <script type="text/javascript">

        $(window).load(function() {
            $('.flexslider').flexslider({
                animation: "slide",
                directionNav: false,
                slideshow: false,
                start: function(slider) {
                    $('body').removeClass('loading');
                }
            });
        });
    </script>

    <script type="text/javascript">
        $(window).scroll(function() {
            var posicion = $(window).scrollTop();

            if (posicion >= 80) {
                $('header').addClass('fijo');
                $('.top-bar ul li').addClass('fijo');
                $('.secciones').addClass('fix');
            }
            else {
                $('header').removeClass('fijo');
                $('.top-bar ul li').removeClass('fijo');
                $('.secciones').removeClass('fix');
            }

        });
    </script>


    <!-- Optional FlexSlider Additions -->
    <script src="/mundial-brasil-2014/js/jsCalendario/jquery.easing.js"></script>
    <script src="/mundial-brasil-2014/js/jsCalendario/jquery.mousewheel.js"></script>
    <script src="/mundial-brasil-2014/js/jsCalendario/mundial-mobile.js"></script>



    <!-- Dialogo lugar fecha y hora -->
    <script type="text/javascript" src="/mundial-brasil-2014/js/jquery-1.6.min.js"></script>
    <script type="text/javascript" src="/mundial-brasil-2014/js/jsCalendario/jquery.reveal.js"></script>


    <!-- Acordeon  -->
    <script src="/mundial-brasil-2014/js/jquery-1.9.1.js"></script>
    <script src="/mundial-brasil-2014/js/jquery-ui.js"></script>
    <script>
        $(document).ready(function() {
            $("#accordion").accordion({heightStyle: "content"});
            $("#accordion").accordion({collapsible: true});
            $("#accordion").accordion({active: false});

        });
    </script>

    <?php
    $referer = '';
    if (isset($_SERVER['HTTP_REFERER'])):
        $referer = $_SERVER['HTTP_REFERER'];
    endif;
    ?>
    <!-- SiteCatalyst code version: H.25.3.
         Copyright 1996-2013 Adobe, Inc. All Rights Reserved
         More info available at http://www.omniture.com -->
    <img src="http://eltiempo.112.2o7.net/b/ss/eltiempoeltiempomovil,eltiempoglobal/5/H.25.3--WAP/489?pageName=Grupos&ch=calendario&r=<?php print $referer; ?>" height="1" width="1" border="0" alt="" style="position:absolute"></img>
    <!-- End SiteCatalyst code version: H.25.3. -->

</body>​