<!-- CSS Styles -->
<link rel="stylesheet" href="/mundial-brasil-2014/css/cssCalendario/resetCalendario.css" type="text/css" media="screen" />
<link rel="stylesheet" href="/mundial-brasil-2014/css/cssCalendario/flexsliderCalendario.css" type="text/css" media="screen" />
<link rel="stylesheet" href="/mundial-brasil-2014/css/cssCalendario/generalesCalendario.css" type="text/css" media="screen" />
<link rel="stylesheet" href="/mundial-brasil-2014/css/cssCalendario/homeCalendario.css" type="text/css" media="screen" />


<!-- Styles calenbdario desktop 
================================================== -->
<link rel="stylesheet" href="/mundial-brasil-2014/css/cssCalendario/resetCalendario.css">
<link rel="stylesheet" href="/mundial-brasil-2014/css/cssCalendario/styleCalendario.css">
<link rel="stylesheet" href="/mundial-brasil-2014/css/cssCalendario/styleCalendario2.css">
<link rel="stylesheet" type="text/css" href="/mundial-brasil-2014/css/cssCalendario/New_pronosticoCalendario.css">

<!-- Javascript -->
<script src="/mundial-brasil-2014/js/jsCalendario/modernizr.js"></script>

<!-- Dialogo botonera por grupos -->
<script type="text/javascript" src="/mundial-brasil-2014/js/jquery-1.6.min.js"></script>
<script type="text/javascript" src="/mundial-brasil-2014/js/jsCalendario/jquery.reveal.js"></script>

<title>Calendario Mundial Brasil 2014</title>  
<meta name="description" content="Calendario y Horarios de los partidos del mundial Brasil 2014. Fecha y Hora de los partidos.">
<meta name="keywords" content="calendario, cronograma, partidos, horas, estadios, mundial, brasil, futbol, deportes, mundial">


<meta property="og:title" content="Calendario Mundial Brasil 2014" />
<meta property="og:type" content="website" />
<meta property="og:url" content="http://m.eltiempo.com/mundial-brasil-2014/calendario" />
<meta property="og:description" content="Vea aquí la programación de los partidos en el especial multimedia del Mundial Brasil 2014" />
<meta property="og:image" content="http://m.eltiempo.com/mundial-brasil-2014/img/imagen_compartir.jpg" />
<meta property="fb:admins" content="100002279652972" />

</head>

<body>

    <div class="container">

        <div class="content">

            <?php print $this->header(); ?>

            <div class="secciones">

                <div id="overlay" class="overlay"></div>

                <section class="tabla_clasificacionM">

                    <div class="tit_tablaM">

                        <h3 class="tituloCalen">CALENDARIO</h3>

                    </div>

                </section>

                <section class="social">

                    <div class="compartir">

                        <ul>

                            <li><p>Compartir</p></li>

                            <li><a class="facebook" href="http://www.facebook.com/sharer.php?u=http://m.eltiempo.com/mundial-brasil-2014/calendario" target="_blank">Facebook</a></li>
                            <li><a class="twitter" href="https://twitter.com/share?url=http://www.facebook.com/sharer.php?u=http://m.eltiempo.com/mundial-brasil-2014/calendario&via=ELTIEMPO&text=Vea aquí la programación de los partidos en el especial multimedia del Mundial Brasil 2014" target="_blank">Twitter</a></li>
                            <li><a class="correo" href="#">Correo</a></li>
                        </ul>

                    </div>

                </section>

            </div>

            <!----------------- POPUPS menu por grupos-------------------------->

            <div id="a1" class="reveal-modal small">

                <div class="botoneraCalendario">


                    <a class="btnTabla a"></a>

                    <a class="btnTabla b"></a>

                    <a class="btnTabla c"></a>

                    <a class="btnTabla d"></a>

                    <a class="btnTabla e"></a>

                    <a class="btnTabla f"></a>

                    <a class="btnTabla g"></a>

                    <a class="btnTabla h"></a>

                    <a class="btnTodosGrupos">Ver todos los Grupos</a>

                </div>

                <a class="close-reveal-modal">&#215;</a>

            </div>

            <div id="06-12" class="contenCalendario">

                <div class="cajaFecha">

                    <li class="fechaCalendario">

                        <h4>Junio</h4>

                        <p>12</p>

                    </li>

                </div>

                <li class="partidosCalendario grupoa">

                    <div class="todos-los-equipos">

                        <div class="grupo">

                            <div class="tabla-completa">                  

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p bra"></span>BRA</li>

                                </ul>

                                <ul class="marcadorFase">

                                    <li>0</li>

                                    <li>(0)</li>

                                    <li class="vs">vs</li>

                                    <li>0</li>

                                    <li>(0)</li>

                                </ul>

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p cro"></span>CRO</li>

                                </ul>

                            </div>

                        </div>

                    </div>

                </li>

            </div>


            <div id="06-13" class="contenCalendario ">

                <div class="cajaFecha">

                    <li class="fechaCalendario">

                        <h4>Junio</h4>

                        <p>13</p>

                    </li>

                </div>

                <li class="partidosCalendario grupoa">

                    <div class="todos-los-equipos">

                        <div class="grupo">

                            <div class="tabla-completa">                  

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p mex"></span>MEX</li>

                                </ul>

                                <ul class="marcadorFase">

                                    <li>0</li>

                                    <li>(0)</li>

                                    <li class="vs">vs</li>

                                    <li>0</li>

                                    <li>(0)</li>

                                </ul>

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p cam"></span>CAM</li>

                                </ul>

                            </div>

                        </div>

                    </div>

                </li>


                <li class="partidosCalendario grupob">

                    <div class="todos-los-equipos">

                        <div class="grupo">

                            <div class="tabla-completa">                  

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p esp"></span>ESP</li>

                                </ul>

                                <ul class="marcadorFase">

                                    <li>0</li>

                                    <li>(0)</li>

                                    <li class="vs">vs</li>

                                    <li>0</li>

                                    <li>(0)</li>

                                </ul>

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p cam"></span>CAM</li>

                                </ul>

                            </div>

                        </div>

                    </div>

                </li>

                <li class="partidosCalendario grupob">

                    <div class="todos-los-equipos">

                        <div class="grupo">

                            <div class="tabla-completa">                  

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p chi"></span>CHI</li>

                                </ul>

                                <ul class="marcadorFase">

                                    <li>0</li>

                                    <li>(0)</li>

                                    <li class="vs">vs</li>

                                    <li>0</li>

                                    <li>(0)</li>

                                </ul>

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p aus"></span>AUS</li>

                                </ul>

                            </div>

                        </div>

                    </div>

                </li>

            </div>


            <div id="06-14" class="contenCalendario">

                <div class="cajaFecha">

                    <li class="fechaCalendario">

                        <h4>Junio</h4>

                        <p>14</p>

                    </li>

                </div>

                <li class="partidosCalendario grupoc">

                    <div class="todos-los-equipos">

                        <div class="grupo">

                            <div class="tabla-completa">                  

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p col"></span>COL</li>

                                </ul>

                                <ul class="marcadorFase">

                                    <li>0</li>

                                    <li>(0)</li>

                                    <li class="vs">vs</li>

                                    <li>0</li>

                                    <li>(0)</li>

                                </ul>

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p gre"></span>GRE</li>

                                </ul>

                            </div>

                        </div>

                    </div>

                </li>


                <li class="partidosCalendario grupod">

                    <div class="todos-los-equipos">

                        <div class="grupo">

                            <div class="tabla-completa">                  

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p uru"></span>URU</li>

                                </ul>

                                <ul class="marcadorFase">

                                    <li>0</li>

                                    <li>(0)</li>

                                    <li class="vs">vs</li>

                                    <li>0</li>

                                    <li>(0)</li>

                                </ul>

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p crc"></span>CRC</li>

                                </ul>

                            </div>

                        </div>

                    </div>

                </li>


                <li class="partidosCalendario grupod">

                    <div class="todos-los-equipos">

                        <div class="grupo">

                            <div class="tabla-completa">                  

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p ing"></span>ING</li>

                                </ul>

                                <ul class="marcadorFase">

                                    <li>0</li>

                                    <li>(0)</li>

                                    <li class="vs">vs</li>

                                    <li>0</li>

                                    <li>(0)</li>

                                </ul>

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p ita"></span>ITA</li>

                                </ul>

                            </div>

                        </div>

                    </div>

                </li>


                <li class="partidosCalendario grupoc">

                    <div class="todos-los-equipos">

                        <div class="grupo">

                            <div class="tabla-completa">                  

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p cdm"></span>CDM</li>

                                </ul>

                                <ul class="marcadorFase">

                                    <li>0</li>

                                    <li>(0)</li>

                                    <li class="vs">vs</li>

                                    <li>0</li>

                                    <li>(0)</li>

                                </ul>

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p jap"></span>JAP</li>

                                </ul>

                            </div>

                        </div>

                    </div>

                </li>

            </div>


            <div id="06-15" class="contenCalendario">

                <div class="cajaFecha">

                    <li class="fechaCalendario">

                        <h4>Junio</h4>

                        <p>15</p>

                    </li>

                </div>


                <li class="partidosCalendario grupoe">

                    <div class="todos-los-equipos">

                        <div class="grupo">

                            <div class="tabla-completa">                  

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p sui"></span>SUI</li>

                                </ul>

                                <ul class="marcadorFase">

                                    <li>0</li>

                                    <li>(0)</li>

                                    <li class="vs">vs</li>

                                    <li>0</li>

                                    <li>(0)</li>

                                </ul>

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p ecu"></span>ECU</li>

                                </ul>

                            </div>

                        </div>

                    </div>

                </li>


                <li class="partidosCalendario grupoe">

                    <div class="todos-los-equipos">

                        <div class="grupo">

                            <div class="tabla-completa">                  

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p fra"></span>FRA</li>

                                </ul>

                                <ul class="marcadorFase">

                                    <li>0</li>

                                    <li>(0)</li>

                                    <li class="vs">vs</li>

                                    <li>0</li>

                                    <li>(0)</li>

                                </ul>

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p hon"></span>HON</li>

                                </ul>

                            </div>

                        </div>

                    </div>

                </li>


                <li class="partidosCalendario grupof">

                    <div class="todos-los-equipos">

                        <div class="grupo">

                            <div class="tabla-completa">                  

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p arg"></span>ARG</li>

                                </ul>

                                <ul class="marcadorFase">

                                    <li>0</li>

                                    <li>(0)</li>

                                    <li class="vs">vs</li>

                                    <li>0</li>

                                    <li>(0)</li>

                                </ul>

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p bos"></span>BOS</li>

                                </ul>

                            </div>

                        </div>

                    </div>

                </li>

            </div>


            <div id="06-16" class="contenCalendario">

                <div class="cajaFecha">

                    <li class="fechaCalendario">

                        <h4>Junio</h4>

                        <p>16</p>

                    </li>

                </div>


                <li class="partidosCalendario grupog">

                    <div class="todos-los-equipos">

                        <div class="grupo">

                            <div class="tabla-completa">                  

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p ale"></span>ALE</li>

                                </ul>

                                <ul class="marcadorFase">

                                    <li>0</li>

                                    <li>(0)</li>

                                    <li class="vs">vs</li>

                                    <li>0</li>

                                    <li>(0)</li>

                                </ul>

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p por"></span>POR</li>

                                </ul>

                            </div>

                        </div>

                    </div>

                </li>


                <li class="partidosCalendario grupof">

                    <div class="todos-los-equipos">

                        <div class="grupo">

                            <div class="tabla-completa">                  

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p irn"></span>IRN</li>

                                </ul>

                                <ul class="marcadorFase">

                                    <li>0</li>

                                    <li>(0)</li>

                                    <li class="vs">vs</li>

                                    <li>0</li>

                                    <li>(0)</li>

                                </ul>

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p nig"></span>NIG</li>

                                </ul>

                            </div>

                        </div>

                    </div>

                </li>


                <li class="partidosCalendario grupog">

                    <div class="todos-los-equipos">

                        <div class="grupo">

                            <div class="tabla-completa">                  

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p gha"></span>GHA</li>

                                </ul>

                                <ul class="marcadorFase">

                                    <li>0</li>

                                    <li>(0)</li>

                                    <li class="vs">vs</li>

                                    <li>0</li>

                                    <li>(0)</li>

                                </ul>

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p eua"></span>EUA</li>

                                </ul>

                            </div>

                        </div>

                    </div>

                </li>

            </div>



            <div id="06-17" class="contenCalendario">

                <div class="cajaFecha">

                    <li class="fechaCalendario">

                        <h4>Junio</h4>

                        <p>17</p>

                    </li>

                </div>


                <li class="partidosCalendario grupoh">

                    <div class="todos-los-equipos">

                        <div class="grupo">

                            <div class="tabla-completa">                  

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p bel"></span>BEL</li>

                                </ul>

                                <ul class="marcadorFase">

                                    <li>0</li>

                                    <li>(0)</li>

                                    <li class="vs">vs</li>

                                    <li>0</li>

                                    <li>(0)</li>

                                </ul>

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p agl"></span>AGL</li>

                                </ul>

                            </div>

                        </div>

                    </div>

                </li>


                <li class="partidosCalendario grupoa">

                    <div class="todos-los-equipos">

                        <div class="grupo">

                            <div class="tabla-completa">                  

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p bra"></span>BRA</li>

                                </ul>

                                <ul class="marcadorFase">

                                    <li>0</li>

                                    <li>(0)</li>

                                    <li class="vs">vs</li>

                                    <li>0</li>

                                    <li>(0)</li>

                                </ul>

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p mex"></span>MEX</li>

                                </ul>

                            </div>

                        </div>

                    </div>

                </li>


                <li class="partidosCalendario grupoh">

                    <div class="todos-los-equipos">

                        <div class="grupo">

                            <div class="tabla-completa">                  

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p cor"></span>COR</li>

                                </ul>

                                <ul class="marcadorFase">

                                    <li>0</li>

                                    <li>(0)</li>

                                    <li class="vs">vs</li>

                                    <li>0</li>

                                    <li>(0)</li>

                                </ul>

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p rus"></span>RUS</li>

                                </ul>

                            </div>

                        </div>

                    </div>

                </li>

            </div>


            <div id="06-18" class="contenCalendario">

                <div class="cajaFecha">

                    <li class="fechaCalendario">

                        <h4>Junio</h4>

                        <p>18</p>

                    </li>

                </div>


                <li class="partidosCalendario grupob">

                    <div class="todos-los-equipos">

                        <div class="grupo">

                            <div class="tabla-completa">                  

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p aus"></span>AUS</li>

                                </ul>

                                <ul class="marcadorFase">

                                    <li>0</li>

                                    <li>(0)</li>

                                    <li class="vs">vs</li>

                                    <li>0</li>

                                    <li>(0)</li>

                                </ul>

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p hol"></span>HOL</li>

                                </ul>

                            </div>

                        </div>

                    </div>

                </li>


                <li class="partidosCalendario grupob">

                    <div class="todos-los-equipos">

                        <div class="grupo">

                            <div class="tabla-completa">                  

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p esp"></span>ESP</li>

                                </ul>

                                <ul class="marcadorFase">

                                    <li>0</li>

                                    <li>(0)</li>

                                    <li class="vs">vs</li>

                                    <li>0</li>

                                    <li>(0)</li>

                                </ul>

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p chi"></span>CHI</li>

                                </ul>

                            </div>

                        </div>

                    </div>

                </li>


                <li class="partidosCalendario grupoa">

                    <div class="todos-los-equipos">

                        <div class="grupo">

                            <div class="tabla-completa">                  

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p cam"></span>CAM</li>

                                </ul>

                                <ul class="marcadorFase">

                                    <li>0</li>

                                    <li>(0)</li>

                                    <li class="vs">vs</li>

                                    <li>0</li>

                                    <li>(0)</li>

                                </ul>

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p cro"></span>CRO</li>

                                </ul>

                            </div>

                        </div>

                    </div>

                </li>

            </div>


            <div id="06-19" class="contenCalendario">

                <div class="cajaFecha">

                    <li class="fechaCalendario">

                        <h4>Junio</h4>

                        <p>19</p>

                    </li>

                </div>


                <li class="partidosCalendario grupoc">

                    <div class="todos-los-equipos">

                        <div class="grupo">

                            <div class="tabla-completa">                  

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p col"></span>COL</li>

                                </ul>

                                <ul class="marcadorFase">

                                    <li>0</li>

                                    <li>(0)</li>

                                    <li class="vs">vs</li>

                                    <li>0</li>

                                    <li>(0)</li>

                                </ul>

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p cdm"></span>CDM</li>

                                </ul>

                            </div>

                        </div>

                    </div>

                </li>


                <li class="partidosCalendario grupod">

                    <div class="todos-los-equipos">

                        <div class="grupo">

                            <div class="tabla-completa">                  

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p uru"></span>URU</li>

                                </ul>

                                <ul class="marcadorFase">

                                    <li>0</li>

                                    <li>(0)</li>

                                    <li class="vs">vs</li>

                                    <li>0</li>

                                    <li>(0)</li>

                                </ul>

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p ing"></span>ING</li>

                                </ul>

                            </div>

                        </div>

                    </div>

                </li>


                <li class="partidosCalendario grupoc">

                    <div class="todos-los-equipos">

                        <div class="grupo">

                            <div class="tabla-completa">                  

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p jap"></span>JAP</li>

                                </ul>

                                <ul class="marcadorFase">

                                    <li>0</li>

                                    <li>(0)</li>

                                    <li class="vs">vs</li>

                                    <li>0</li>

                                    <li>(0)</li>

                                </ul>

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p gre"></span>GRE</li>

                                </ul>

                            </div>

                        </div>

                    </div>

                </li>

            </div>


            <div id="06-20" class="contenCalendario grupod">

                <div class="cajaFecha">

                    <li class="fechaCalendario">

                        <h4>Junio</h4>

                        <p>20</p>

                    </li>

                </div>


                <li class="partidosCalendario">

                    <div class="todos-los-equipos">

                        <div class="grupo">

                            <div class="tabla-completa">                  

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p ita"></span>ITA</li>

                                </ul>

                                <ul class="marcadorFase">

                                    <li>0</li>

                                    <li>(0)</li>

                                    <li class="vs">vs</li>

                                    <li>0</li>

                                    <li>(0)</li>

                                </ul>

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p cro"></span>CRO</li>

                                </ul>

                            </div>

                        </div>

                    </div>

                </li>


                <li class="partidosCalendario grupoe">

                    <div class="todos-los-equipos">

                        <div class="grupo">

                            <div class="tabla-completa">                  

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p sui"></span>SUI</li>

                                </ul>

                                <ul class="marcadorFase">

                                    <li>0</li>

                                    <li>(0)</li>

                                    <li class="vs">vs</li>

                                    <li>0</li>

                                    <li>(0)</li>

                                </ul>

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p fra"></span>FRA</li>

                                </ul>

                            </div>

                        </div>

                    </div>

                </li>


                <li class="partidosCalendario grupoe">

                    <div class="todos-los-equipos">

                        <div class="grupo">

                            <div class="tabla-completa">                  

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p hon"></span>HON</li>

                                </ul>

                                <ul class="marcadorFase">

                                    <li>0</li>

                                    <li>(0)</li>

                                    <li class="vs">vs</li>

                                    <li>0</li>

                                    <li>(0)</li>

                                </ul>

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p ecu"></span>ECU</li>

                                </ul>

                            </div>

                        </div>

                    </div>

                </li>

            </div>


            <div id="06-21" class="contenCalendario">

                <div class="cajaFecha">

                    <li class="fechaCalendario">

                        <h4>Junio</h4>

                        <p>21</p>

                    </li>

                </div>


                <li class="partidosCalendario grupof">

                    <div class="todos-los-equipos">

                        <div class="grupo">

                            <div class="tabla-completa">                  

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p arg"></span>ARG</li>

                                </ul>

                                <ul class="marcadorFase">

                                    <li>0</li>

                                    <li>(0)</li>

                                    <li class="vs">vs</li>

                                    <li>0</li>

                                    <li>(0)</li>

                                </ul>

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p irn"></span>IRN</li>

                                </ul>

                            </div>

                        </div>

                    </div>

                </li>


                <li class="partidosCalendario grupog">

                    <div class="todos-los-equipos">

                        <div class="grupo">

                            <div class="tabla-completa">                  

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p ale"></span>ALE</li>

                                </ul>

                                <ul class="marcadorFase">

                                    <li>0</li>

                                    <li>(0)</li>

                                    <li class="vs">vs</li>

                                    <li>0</li>

                                    <li>(0)</li>

                                </ul>

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p gha"></span>GHA</li>

                                </ul>

                            </div>

                        </div>

                    </div>

                </li>


                <li class="partidosCalendario grupof">

                    <div class="todos-los-equipos">

                        <div class="grupo">

                            <div class="tabla-completa">                  

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p nig"></span>NIG</li>

                                </ul>

                                <ul class="marcadorFase">

                                    <li>0</li>

                                    <li>(0)</li>

                                    <li class="vs">vs</li>

                                    <li>0</li>

                                    <li>(0)</li>

                                </ul>

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p bos"></span>BOS</li>

                                </ul>

                            </div>

                        </div>

                    </div>

                </li>

            </div>


            <div id="06-22" class="contenCalendario">

                <div class="cajaFecha">

                    <li class="fechaCalendario">

                        <h4>Junio</h4>

                        <p>22</p>

                    </li>

                </div>


                <li class="partidosCalendario grupoh">

                    <div class="todos-los-equipos">

                        <div class="grupo">

                            <div class="tabla-completa">                  

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p bel"></span>BEL</li>

                                </ul>

                                <ul class="marcadorFase">

                                    <li>0</li>

                                    <li>(0)</li>

                                    <li class="vs">vs</li>

                                    <li>0</li>

                                    <li>(0)</li>

                                </ul>

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p rus"></span>RUS</li>

                                </ul>

                            </div>

                        </div>

                    </div>

                </li>


                <li class="partidosCalendario grupoh">

                    <div class="todos-los-equipos">

                        <div class="grupo">

                            <div class="tabla-completa">                  

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p cor"></span>COR</li>

                                </ul>

                                <ul class="marcadorFase">

                                    <li>0</li>

                                    <li>(0)</li>

                                    <li class="vs">vs</li>

                                    <li>0</li>

                                    <li>(0)</li>

                                </ul>

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p agl"></span>AGL</li>

                                </ul>

                            </div>

                        </div>

                    </div>

                </li>


                <li class="partidosCalendario grupoe">

                    <div class="todos-los-equipos">

                        <div class="grupo">

                            <div class="tabla-completa">                  

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p eua"></span>EUA</li>

                                </ul>

                                <ul class="marcadorFase">

                                    <li>0</li>

                                    <li>(0)</li>

                                    <li class="vs">vs</li>

                                    <li>0</li>

                                    <li>(0)</li>

                                </ul>

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p por"></span>POR</li>

                                </ul>

                            </div>

                        </div>

                    </div>

                </li>

            </div>


            <div id="06-23" class="contenCalendario">

                <div class="cajaFecha">

                    <li class="fechaCalendario">

                        <h4>Junio</h4>

                        <p>23</p>

                    </li>

                </div>


                <li class="partidosCalendario grupob">

                    <div class="todos-los-equipos">

                        <div class="grupo">

                            <div class="tabla-completa">                  

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p aus"></span>AUS</li>

                                </ul>

                                <ul class="marcadorFase">

                                    <li>0</li>

                                    <li>(0)</li>

                                    <li class="vs">vs</li>

                                    <li>0</li>

                                    <li>(0)</li>

                                </ul>

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p esp"></span>ESP</li>

                                </ul>

                            </div>

                        </div>

                    </div>

                </li>


                <li class="partidosCalendario grupob">

                    <div class="todos-los-equipos">

                        <div class="grupo">

                            <div class="tabla-completa">                  

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p hol"></span>HOL</li>

                                </ul>

                                <ul class="marcadorFase">

                                    <li>0</li>

                                    <li>(0)</li>

                                    <li class="vs">vs</li>

                                    <li>0</li>

                                    <li>(0)</li>

                                </ul>

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p chi"></span>CHI</li>

                                </ul>

                            </div>

                        </div>

                    </div>

                </li>


                <li class="partidosCalendario grupoa">

                    <div class="todos-los-equipos">

                        <div class="grupo">

                            <div class="tabla-completa">                  

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p mex"></span>MEX</li>

                                </ul>

                                <ul class="marcadorFase">

                                    <li>0</li>

                                    <li>(0)</li>

                                    <li class="vs">vs</li>

                                    <li>0</li>

                                    <li>(0)</li>

                                </ul>

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p cro"></span>CRO</li>

                                </ul>

                            </div>

                        </div>

                    </div>

                </li>


                <li class="partidosCalendario grupoa">

                    <div class="todos-los-equipos">

                        <div class="grupo">

                            <div class="tabla-completa">                  

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p cdm"></span>CDM</li>

                                </ul>

                                <ul class="marcadorFase">

                                    <li>0</li>

                                    <li>(0)</li>

                                    <li class="vs">vs</li>

                                    <li>0</li>

                                    <li>(0)</li>

                                </ul>

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p bra"></span>BRA</li>

                                </ul>

                            </div>

                        </div>

                    </div>

                </li>

            </div>


            <div id="06-24" class="contenCalendario">

                <div class="cajaFecha">

                    <li class="fechaCalendario">

                        <h4>Junio</h4>

                        <p>24</p>

                    </li>

                </div>


                <li class="partidosCalendario grupod">

                    <div class="todos-los-equipos">

                        <div class="grupo">

                            <div class="tabla-completa">                  

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p crc"></span>CRC</li>

                                </ul>

                                <ul class="marcadorFase">

                                    <li>0</li>

                                    <li>(0)</li>

                                    <li class="vs">vs</li>

                                    <li>0</li>

                                    <li>(0)</li>

                                </ul>

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p ing"></span>ING</li>

                                </ul>

                            </div>

                        </div>

                    </div>

                </li>


                <li class="partidosCalendario grupod">

                    <div class="todos-los-equipos">

                        <div class="grupo">

                            <div class="tabla-completa">                  

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p ita"></span>ITA</li>

                                </ul>

                                <ul class="marcadorFase">

                                    <li>0</li>

                                    <li>(0)</li>

                                    <li class="vs">vs</li>

                                    <li>0</li>

                                    <li>(0)</li>

                                </ul>

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p uru"></span>URU</li>

                                </ul>

                            </div>

                        </div>

                    </div>

                </li>


                <li class="partidosCalendario grupoc">

                    <div class="todos-los-equipos">

                        <div class="grupo">

                            <div class="tabla-completa">                  

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p jap"></span>JAP</li>

                                </ul>

                                <ul class="marcadorFase">

                                    <li>0</li>

                                    <li>(0)</li>

                                    <li class="vs">vs</li>

                                    <li>0</li>

                                    <li>(0)</li>

                                </ul>

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p col"></span>COL</li>

                                </ul>

                            </div>

                        </div>

                    </div>

                </li>


                <li class="partidosCalendario grupoc">

                    <div class="todos-los-equipos">

                        <div class="grupo">

                            <div class="tabla-completa">                  

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p gre"></span>GRE</li>

                                </ul>

                                <ul class="marcadorFase">

                                    <li>0</li>

                                    <li>(0)</li>

                                    <li class="vs">vs</li>

                                    <li>0</li>

                                    <li>(0)</li>

                                </ul>

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p cdm"></span>CDM</li>

                                </ul>

                            </div>

                        </div>

                    </div>

                </li>

            </div>


            <div id="06-25" class="contenCalendario">

                <div class="cajaFecha">

                    <li class="fechaCalendario">

                        <h4>Junio</h4>

                        <p>25</p>

                    </li>

                </div>


                <li class="partidosCalendario grupof">

                    <div class="todos-los-equipos">

                        <div class="grupo">

                            <div class="tabla-completa">                  

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p nig"></span>NIG</li>

                                </ul>

                                <ul class="marcadorFase">

                                    <li>0</li>

                                    <li>(0)</li>

                                    <li class="vs">vs</li>

                                    <li>0</li>

                                    <li>(0)</li>

                                </ul>

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p arg"></span>ARG</li>

                                </ul>

                            </div>

                        </div>

                    </div>

                </li>


                <li class="partidosCalendario grupof">

                    <div class="todos-los-equipos">

                        <div class="grupo">

                            <div class="tabla-completa">                  

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p bos"></span>BOS</li>

                                </ul>

                                <ul class="marcadorFase">

                                    <li>0</li>

                                    <li>(0)</li>

                                    <li class="vs">vs</li>

                                    <li>0</li>

                                    <li>(0)</li>

                                </ul>

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p irn"></span>IRN</li>

                                </ul>

                            </div>

                        </div>

                    </div>

                </li>


                <li class="partidosCalendario grupoe">

                    <div class="todos-los-equipos">

                        <div class="grupo">

                            <div class="tabla-completa">                  

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p hon"></span>HON</li>

                                </ul>

                                <ul class="marcadorFase">

                                    <li>0</li>

                                    <li>(0)</li>

                                    <li class="vs">vs</li>

                                    <li>0</li>

                                    <li>(0)</li>

                                </ul>

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p sui"></span>SUI</li>

                                </ul>

                            </div>

                        </div>

                    </div>

                </li>


                <li class="partidosCalendario grupoe">

                    <div class="todos-los-equipos">

                        <div class="grupo">

                            <div class="tabla-completa">                  

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p ecu"></span>ECU</li>

                                </ul>

                                <ul class="marcadorFase">

                                    <li>0</li>

                                    <li>(0)</li>

                                    <li class="vs">vs</li>

                                    <li>0</li>

                                    <li>(0)</li>

                                </ul>

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p fra"></span>FRA</li>

                                </ul>

                            </div>

                        </div>

                    </div>

                </li>

            </div>


            <div id="06-26" class="contenCalendario">

                <div class="cajaFecha">

                    <li class="fechaCalendario">

                        <h4>Junio</h4>

                        <p>26</p>

                    </li>

                </div>


                <li class="partidosCalendario grupog">

                    <div class="todos-los-equipos">

                        <div class="grupo">

                            <div class="tabla-completa">                  

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p por"></span>POR</li>

                                </ul>

                                <ul class="marcadorFase">

                                    <li>0</li>

                                    <li>(0)</li>

                                    <li class="vs">vs</li>

                                    <li>0</li>

                                    <li>(0)</li>

                                </ul>

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p gha"></span>GHA</li>

                                </ul>

                            </div>

                        </div>

                    </div>

                </li>


                <li class="partidosCalendario grupog">

                    <div class="todos-los-equipos">

                        <div class="grupo">

                            <div class="tabla-completa">                  

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p eua"></span>EUA</li>

                                </ul>

                                <ul class="marcadorFase">

                                    <li>0</li>

                                    <li>(0)</li>

                                    <li class="vs">vs</li>

                                    <li>0</li>

                                    <li>(0)</li>

                                </ul>

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p ale"></span>ALE</li>

                                </ul>

                            </div>

                        </div>

                    </div>

                </li>


                <li class="partidosCalendario grupoh">

                    <div class="todos-los-equipos">

                        <div class="grupo">

                            <div class="tabla-completa">                  

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p cor"></span>COR</li>

                                </ul>

                                <ul class="marcadorFase">

                                    <li>0</li>

                                    <li>(0)</li>

                                    <li class="vs">vs</li>

                                    <li>0</li>

                                    <li>(0)</li>

                                </ul>

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p bel"></span>BEL</li>

                                </ul>

                            </div>

                        </div>

                    </div>

                </li>


                <li class="partidosCalendario grupoh">

                    <div class="todos-los-equipos">

                        <div class="grupo">

                            <div class="tabla-completa">                  

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p agl"></span>AGL</li>

                                </ul>

                                <ul class="marcadorFase">

                                    <li>0</li>

                                    <li>(0)</li>

                                    <li class="vs">vs</li>

                                    <li>0</li>

                                    <li>(0)</li>

                                </ul>

                                <ul class="tabla-paisFase">

                                    <li><span class="pais-p rus"></span>RUS</li>

                                </ul>

                            </div>

                        </div>

                    </div>

                </li>

            </div>

            <div id="06-27" class="contenCalendario descanso">

                <div class="cajaFecha">

                    <li class="fechaCalendario">

                        <h4>Junio</h4>

                        <p>27</p>

                    </li>

                </div>

            </div>



            <div id="06-28" class="contenCalendario">

                <div class="cajaFecha">

                    <li class="fechaCalendario">

                        <h4>Junio</h4>

                        <p>28</p>

                    </li>

                </div>

                <li class="fasesTitulo">Octavos</li>

                <li class="partidosCalendario">

                    <div class="todos-los-equipos">

                        <div class="grupo">

                            <div class="tabla-completa">                  

                                <ul class="tabla-paisFase">

                                    <li>1A</li>

                                </ul>

                                <ul class="marcadorFase">

                                    <li>0</li>

                                    <li>(0)</li>

                                    <li class="vs">vs</li>

                                    <li>0</li>

                                    <li>(0)</li>

                                </ul>

                                <ul class="tabla-paisFase">

                                    <li>2B</li>

                                </ul>

                            </div>

                        </div>

                    </div>

                </li>


                <li class="partidosCalendario">

                    <div class="todos-los-equipos">

                        <div class="grupo">

                            <div class="tabla-completa">                  

                                <ul class="tabla-paisFase">

                                    <li>1C</li>

                                </ul>

                                <ul class="marcadorFase">

                                    <li>0</li>

                                    <li>(0)</li>

                                    <li class="vs">vs</li>

                                    <li>0</li>

                                    <li>(0)</li>

                                </ul>

                                <ul class="tabla-paisFase">

                                    <li>2D</li>

                                </ul>

                            </div>

                        </div>

                    </div>

                </li>

            </div>



            <div id="06-29" class="contenCalendario">

                <div class="cajaFecha">

                    <li class="fechaCalendario">

                        <h4>Junio</h4>

                        <p>29</p>

                    </li>

                </div>

                <li class="fasesTitulo">Octavos</li>

                <li class="partidosCalendario">

                    <div class="todos-los-equipos">

                        <div class="grupo">

                            <div class="tabla-completa">                  

                                <ul class="tabla-paisFase">

                                    <li>1B</li>

                                </ul>

                                <ul class="marcadorFase">

                                    <li>0</li>

                                    <li>(0)</li>

                                    <li class="vs">vs</li>

                                    <li>0</li>

                                    <li>(0)</li>

                                </ul>

                                <ul class="tabla-paisFase">

                                    <li>2A</li>

                                </ul>

                            </div>

                        </div>

                    </div>

                </li>


                <li class="partidosCalendario">

                    <div class="todos-los-equipos">

                        <div class="grupo">

                            <div class="tabla-completa">                  

                                <ul class="tabla-paisFase">

                                    <li>1D</li>

                                </ul>

                                <ul class="marcadorFase">

                                    <li>0</li>

                                    <li>(0)</li>

                                    <li class="vs">vs</li>

                                    <li>0</li>

                                    <li>(0)</li>

                                </ul>

                                <ul class="tabla-paisFase">

                                    <li>2C</li>

                                </ul>

                            </div>

                        </div>

                    </div>

                </li>

            </div>


            <div id="06-30" class="contenCalendario">

                <div class="cajaFecha">

                    <li class="fechaCalendario">

                        <h4>Junio</h4>

                        <p>30</p>

                    </li>

                </div>

                <li class="fasesTitulo">Octavos</li>

                <li class="partidosCalendario">

                    <div class="todos-los-equipos">

                        <div class="grupo">

                            <div class="tabla-completa">                  

                                <ul class="tabla-paisFase">

                                    <li>1E</li>

                                </ul>

                                <ul class="marcadorFase">

                                    <li>0</li>

                                    <li>(0)</li>

                                    <li class="vs">vs</li>

                                    <li>0</li>

                                    <li>(0)</li>

                                </ul>

                                <ul class="tabla-paisFase">

                                    <li>2F</li>

                                </ul>

                            </div>

                        </div>

                    </div>

                </li>


                <li class="partidosCalendario">

                    <div class="todos-los-equipos">

                        <div class="grupo">

                            <div class="tabla-completa">                  

                                <ul class="tabla-paisFase">

                                    <li>1G</li>

                                </ul>

                                <ul class="marcadorFase">

                                    <li>0</li>

                                    <li>(0)</li>

                                    <li class="vs">vs</li>

                                    <li>0</li>

                                    <li>(0)</li>

                                </ul>

                                <ul class="tabla-paisFase">

                                    <li>2H</li>

                                </ul>

                            </div>

                        </div>

                    </div>

                </li>

            </div>


            <div id="07-01" class="contenCalendario">

                <div class="cajaFecha">

                    <li class="fechaCalendario">

                        <h4>Julio</h4>

                        <p>1</p>

                    </li>

                </div>

                <li class="fasesTitulo">Octavos</li>

                <li class="partidosCalendario">

                    <div class="todos-los-equipos">

                        <div class="grupo">

                            <div class="tabla-completa">                  

                                <ul class="tabla-paisFase">

                                    <li>1F</li>

                                </ul>

                                <ul class="marcadorFase">

                                    <li>0</li>

                                    <li>(0)</li>

                                    <li class="vs">vs</li>

                                    <li>0</li>

                                    <li>(0)</li>

                                </ul>

                                <ul class="tabla-paisFase">

                                    <li>2E</li>

                                </ul>

                            </div>

                        </div>

                    </div>

                </li>


                <li class="partidosCalendario">

                    <div class="todos-los-equipos">

                        <div class="grupo">

                            <div class="tabla-completa">                  

                                <ul class="tabla-paisFase">

                                    <li>1H</li>

                                </ul>

                                <ul class="marcadorFase">

                                    <li>0</li>

                                    <li>(0)</li>

                                    <li class="vs">vs</li>

                                    <li>0</li>

                                    <li>(0)</li>

                                </ul>

                                <ul class="tabla-paisFase">

                                    <li>2G</li>

                                </ul>

                            </div>

                        </div>

                    </div>

                </li>

            </div>


            <div id="07-02" class="contenCalendario descanso">

                <div class="cajaFecha">

                    <li class="fechaCalendario">

                        <h4>Julio</h4>

                        <p>2</p>

                    </li>

                </div>

            </div>

            <div id="07-03" class="contenCalendario descanso ">

                <div class="cajaFecha">

                    <li class="fechaCalendario">

                        <h4>Julio</h4>

                        <p>3</p>

                    </li>

                </div>

            </div>


            <div id="07-04" class="contenCalendario">

                <div class="cajaFecha">

                    <li class="fechaCalendario">

                        <h4>Julio</h4>

                        <p>4</p>

                    </li>

                </div>

                <li class="fasesTitulo">Cuartos</li>

                <li class="partidosCalendario">

                    <div class="todos-los-equipos">

                        <div class="grupo">

                            <div class="tabla-completa">                  

                                <ul class="tabla-paisFase">

                                    <li class="ganador">G</li>

                                    <li>1F 2F</li>

                                </ul>

                                <ul class="marcadorFase">

                                    <li>0</li>

                                    <li>(0)</li>

                                    <li class="vs">vs</li>

                                    <li>0</li>

                                    <li>(0)</li>

                                </ul>

                                <ul class="tabla-paisFase">

                                    <li class="ganador">G</li>

                                    <li>1G 2H</li>

                                </ul>

                            </div>

                        </div>

                    </div>

                </li>


                <li class="partidosCalendario">

                    <div class="todos-los-equipos">

                        <div class="grupo">

                            <div class="tabla-completa">                  

                                <ul class="tabla-paisFase">

                                    <li class="ganador">G</li>

                                    <li>1A 2B</li>

                                </ul>

                                <ul class="marcadorFase">

                                    <li>0</li>

                                    <li>(0)</li>

                                    <li class="vs">vs</li>

                                    <li>0</li>

                                    <li>(0)</li>

                                </ul>

                                <ul class="tabla-paisFase">

                                    <li class="ganador">G</li>

                                    <li>1C 2D</li>

                                </ul>

                            </div>

                        </div>

                    </div>

                </li>

            </div>


            <div id="07-05" class="contenCalendario">

                <div class="cajaFecha">

                    <li class="fechaCalendario">

                        <h4>Julio</h4>

                        <p>5</p>

                    </li>

                </div>

                <li class="fasesTitulo">Cuartos</li>

                <li class="partidosCalendario">

                    <div class="todos-los-equipos">

                        <div class="grupo">

                            <div class="tabla-completa">                  

                                <ul class="tabla-paisFase">

                                    <li class="ganador">G</li>

                                    <li>1F 2F</li>

                                </ul>

                                <ul class="marcadorFase">

                                    <li>0</li>

                                    <li>(0)</li>

                                    <li class="vs">vs</li>

                                    <li>0</li>

                                    <li>(0)</li>

                                </ul>

                                <ul class="tabla-paisFase">

                                    <li class="ganador">G</li>

                                    <li>1H 2G</li>

                                </ul>

                            </div>

                        </div>

                    </div>

                </li>


                <li class="partidosCalendario">

                    <div class="todos-los-equipos">

                        <div class="grupo">

                            <div class="tabla-completa">                  

                                <ul class="tabla-paisFase">

                                    <li class="ganador">G</li>

                                    <li>1B 2A</li>

                                </ul>

                                <ul class="marcadorFase">

                                    <li>0</li>

                                    <li>(0)</li>

                                    <li class="vs">vs</li>

                                    <li>0</li>

                                    <li>(0)</li>

                                </ul>

                                <ul class="tabla-paisFase">

                                    <li class="ganador">G</li>

                                    <li>1D 2C</li>

                                </ul>

                            </div>

                        </div>

                    </div>

                </li>

            </div>

            <div id="07-06" class="contenCalendario descanso">

                <div class="cajaFecha">

                    <li class="fechaCalendario">

                        <h4>Julio</h4>

                        <p>6</p>

                    </li>

                </div>

            </div>

            <div id="07-07" class="contenCalendario descanso">

                <div class="cajaFecha">

                    <li class="fechaCalendario">

                        <h4>Julio</h4>

                        <p>7</p>

                    </li>

                </div>

            </div>

            <div id="07-08" class="contenCalendario">

                <div class="cajaFecha">

                    <li class="fechaCalendario">

                        <h4>Julio</h4>

                        <p>8</p>

                    </li>

                </div>

                <li class="fasesTitulo">Semifinal</li>

                <li class="partidosCalendario">

                    <div class="todos-los-equipos">

                        <div class="grupo">

                            <div class="tabla-completa">                  

                                <ul class="tabla-paisFase">

                                    <li>1/4 2</li>

                                </ul>

                                <ul class="marcadorFase">

                                    <li>0</li>

                                    <li>(0)</li>

                                    <li class="vs">vs</li>

                                    <li>0</li>

                                    <li>(0)</li>

                                </ul>

                                <ul class="tabla-paisFase">

                                    <li>1/4 1</li>

                                </ul>

                            </div>

                        </div>

                    </div>

                </li>

            </div>


            <div id="07-09" class="contenCalendario ">

                <div class="cajaFecha">

                    <li class="fechaCalendario">

                        <h4>Julio</h4>

                        <p>9</p>

                    </li>

                </div>

                <li class="fasesTitulo">Semifinal</li>

                <li class="partidosCalendario">

                    <div class="todos-los-equipos">

                        <div class="grupo">

                            <div class="tabla-completa">                  

                                <ul class="tabla-paisFase">

                                    <li>1/4 4</li>

                                </ul>

                                <ul class="marcadorFase">

                                    <li>0</li>

                                    <li>(0)</li>

                                    <li class="vs">vs</li>

                                    <li>0</li>

                                    <li>(0)</li>

                                </ul>

                                <ul class="tabla-paisFase">

                                    <li>1/4 3</li>

                                </ul>

                            </div>

                        </div>

                    </div>

                </li>

            </div>


            <div id="07-10" class="contenCalendario descanso">

                <div class="cajaFecha">

                    <li class="fechaCalendario">

                        <h4>Julio</h4>

                        <p>10</p>

                    </li>

                </div>

            </div>

            <div id="07-11" class="contenCalendario descanso">

                <div class="cajaFecha">

                    <li class="fechaCalendario">

                        <h4>Julio</h4>

                        <p>11</p>

                    </li>

                </div>

            </div>


            <div id="07-12" class="contenCalendario">

                <div class="cajaFecha">

                    <li class="fechaCalendario">

                        <h4>Julio</h4>

                        <p>12</p>

                    </li>

                </div>

                <li class="fasesTitulo">Tercer puesto</li>

                <li class="partidosCalendario">

                    <div class="todos-los-equipos">

                        <div class="grupo">

                            <div class="tabla-completa">                  

                                <ul class="tabla-paisFase">

                                    <li>-</li>

                                </ul>

                                <ul class="marcadorFase">

                                    <li>0</li>

                                    <li>(0)</li>

                                    <li class="vs">vs</li>

                                    <li>0</li>

                                    <li>(0)</li>

                                </ul>

                                <ul class="tabla-paisFase">

                                    <li>-</li>

                                </ul>

                            </div>

                        </div>

                    </div>

                </li>

            </div>


            <div id="07-13" class="contenCalendario">

                <div class="cajaFecha">

                    <li class="fechaCalendario">

                        <h4>Julio</h4>

                        <p>13</p>

                    </li>

                </div>

                <li class="fasesTitulo">Final</li>

                <li class="partidosCalendario">

                    <div class="todos-los-equipos">

                        <div class="grupo">

                            <div class="tabla-completa">                  

                                <ul class="tabla-paisFase">

                                    <li>-</li>

                                </ul>

                                <ul class="marcadorFase">

                                    <li>0</li>

                                    <li>(0)</li>

                                    <li class="vs">vs</li>

                                    <li>0</li>

                                    <li>(0)</li>

                                </ul>

                                <ul class="tabla-paisFase">

                                    <li>-</li>

                                </ul>

                            </div>

                        </div>

                    </div>

                </li>

            </div>


            <?php print $this->footer(); ?>


            <a class="btnVerGrupos" data-animation="fade" data-reveal-id="a1" href="#a1">Ver partidos </br>por grupos</a>        

            <div class="botonesInferiores">


                <a href="calendario/grupos">Grupos</a>

                <a href="calendario/posiciones">Posiciones</a>

            </div>


        </div>

        <?php print $this->menu(); ?>

    </div>





    <!-- jQuery -->

    <script src="/mundial-brasil-2014/js/jquery.min_1.js"></script>

    <script>window.jQuery || document.write('<script src="js/libs/jquery-1.7.min.js">\x3C/script>')</script>


    <!-- FlexSlider -->

    <script defer src="/mundial-brasil-2014/js/jsCalendario/jquery.flexslider.js"></script>


    <script type="text/javascript">


        $(window).load(function() {

            $('.flexslider').flexslider({
                animation: "slide",
                directionNav: false,
                slideshow: false,
                start: function(slider) {

                    $('body').removeClass('loading');

                }

            });

        });

    </script>


    <script type="text/javascript">

        $(window).scroll(function() {

            var posicion = $(window).scrollTop();

            if (posicion >= 80) {

                $('header').addClass('fijo');

                $('.top-bar ul li').addClass('fijo');

                $('.secciones').addClass('fix');

            }

            else {

                $('header').removeClass('fijo');

                $('.top-bar ul li').removeClass('fijo');

                $('.secciones').removeClass('fix');

            }

        });

    </script>

    <!-- Optional FlexSlider Additions -->

    <script src="/mundial-brasil-2014/js/jsCalendario/jquery.easing.js"></script>

    <script src="/mundial-brasil-2014/js/jsCalendario/jquery.mousewheel.js"></script>

    <script src="/mundial-brasil-2014/js/jsCalendario/mundial-mobile.js"></script>


    <script>

        console.log('<?php print date('m-d') ?>');

        jQuery('.contenCalendario').each(function(index) {

            $(this).removeClass('hoy');

        });

        jQuery('#<?php print date('m-d') ?>').addClass('hoy');

    </script>

    <?php
    $referer = '';

    if (isset($_SERVER['HTTP_REFERER'])):

        $referer = $_SERVER['HTTP_REFERER'];

    endif;
    ?>
    <!-- SiteCatalyst code version: H.25.3.
         Copyright 1996-2013 Adobe, Inc. All Rights Reserved
         More info available at http://www.omniture.com -->
    <img src="http://eltiempo.112.2o7.net/b/ss/eltiempoeltiempomovil,eltiempoglobal/5/H.25.3--WAP/489?pageName=Calendario&ch=calendario&r=<?php print $referer; ?>" height="1" width="1" border="0" alt="" style="position:absolute"></img>
    <!-- End SiteCatalyst code version: H.25.3. -->
</body>​