
    <!-- CSS Styles -->
    <link rel="stylesheet" href="/mundial-brasil-2014//css/cssCalendario/resetCalendario.css" type="text/css" media="screen" />
    <link rel="stylesheet" href="/mundial-brasil-2014//css/cssCalendario/flexsliderCalendario.css" type="text/css" media="screen" />
    <link rel="stylesheet" href="/mundial-brasil-2014/css/cssCalendario/generalesCalendario.css" type="text/css" media="screen" />
    <link rel="stylesheet" href="/mundial-brasil-2014/css/cssCalendario/homeCalendario.css" type="text/css" media="screen" />

    <!-- Styles calenbdario desktop 
    ================================================== -->
    <link rel="stylesheet" href="/mundial-brasil-2014/css/cssCalendario/resetCalendario.css">
    <link rel="stylesheet" href="/mundial-brasil-2014/css/cssCalendario/styleCalendario.css">
    <link rel="stylesheet" href="/mundial-brasil-2014/css/cssCalendario/styleCalendario2.css">
    <link rel="stylesheet" type="text/css" href="/mundial-brasil-2014/css/cssCalendario/New_pronosticoCalendario.css">

    <!-- Javascript -->
    <script src="/mundial-brasil-2014/js/jsCalendario/modernizr.js"></script>

    <!-- Dialogo botonera por grupos -->
    <script type="text/javascript" src="/mundial-brasil-2014/js/jquery-1.6.min.js"></script>
    <script type="text/javascript" src="/mundial-brasil-2014/js/jsCalendario/jquery.reveal.js"></script>

    <title>Tabla de Posiciones Mundial Brasil 2014</title>  
    <meta name="description" content=" Información sobre la tabla de posiciones del Mundial Brasil 2014: Puntos, goles y partidos de cada uno de los grupos del mundial.">
    <meta name="keywords" content="calendario, cronograma, partidos, horas, estadios, mundial, brasil, futbol, deportes, mundial, tabla de posiciones">

    <meta property="og:title" content="Grupos Mundial Brasil 2014" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="http://m.eltiempo.com/mundial-brasil-2014/calendario/posiciones" />
    <meta property="og:description" content="Vea aquí los resultados de todos los partidos en el especial multimedia del Mundial Brasil 2014" />
    <meta property="og:image" content="http://m.eltiempo.com/mundial-brasil-2014/img/imagen_compartir.jpg" />
    <meta property="fb:admins" content="100002279652972" />
</head>
<body>
    <div class="container">
        <div class="content">

            <?php print $this->header(); ?>

            <div class="secciones">
                <div id="overlay" class="overlay"></div>
                <section class="tabla_clasificacionM">
                    <div class="tit_tablaM">
                        <h3 class="tituloCalen">POSICIONES</h3>
                    </div>
                </section>
                <section class="social">
                    <div class="compartir">
                        <ul>
                            <li><p>Compartir</p></li>
                            <li><a class="facebook" href="http://www.facebook.com/sharer.php?u=http://m.eltiempo.com/mundial-brasil-2014/calendario/posiciones" target="_blank">Facebook</a></li>
                            <li><a class="twitter" href="https://twitter.com/share?url=http://m.eltiempo.com/mundial-brasil-2014/calendario/posiciones&via=ELTIEMPO&text=Vea aquí los resultados de todos los partidos en el especial multimedia del Mundial Brasil 2014" target="_blank">Twitter</a></li>
                            <li><a class="correo" href="#">Correo</a></li>
                        </ul>
                    </div>
                </section>
            </div>


            <!----------------- POPUPS menu por grupos-------------------------->
            <div id="a1" class="reveal-modal small">
                <div class="botoneraPosiciones">
                    <a href="#ancla1" class="btnTabla a"></a>
                    <a href="#ancla2" class="btnTabla b"></a>
                    <a href="#ancla3" class="btnTabla c"></a>
                    <a href="#ancla4" class="btnTabla d"></a>
                    <a href="#ancla5" class="btnTabla e"></a>	
                    <a href="#ancla6" class="btnTabla f"></a>	
                    <a href="#ancla7" class="btnTabla g"></a>
                    <a href="#ancla8" class="btnTabla h"></a>
                </div>								
                <a class="close-reveal-modal">&#215;</a>
            </div>
            <!--------------------------------------------------->	

            <div class="conteneTablas">	   


                <div class="todos-los-equipos">			
                    <div class="todos-los-equiposTablas">
                        <div id="ancla1" class="grupoTablas a">
                            <div class="tablaDatos ga">
                                <div class="filtro_grupo">
                                    <div class="simbolo-letra2 a"></div>							  							
                                </div>
                                <div class="contenido">					
                                    <div class="tabla-completaTablas">
                                        <div class="filaTablas color-a">					
                                            <ul class="primera-parte">				
                                                <li class="horariosTablasTitulo a">
                                                    <p>											
                                                        <span>PTS</span>
                                                        <span>PJ</span>
                                                        <span>PG</span>
                                                        <span>PE</span>
                                                        <span>PP</span>
                                                        <span>GF</span>
                                                        <span>GC</span>
                                                        <span>GD</span>
                                                    </p>
                                                </li>										
                                            </ul>		
                                        </div>
                                        <div class="filaTablas">
                                            <ul class="primera-parteTablas">	
                                                <span class="pais-pTabla col">Col</span>				
                                                <li class="horariosTablas">
                                                    <p>											
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                    </p>
                                                </li>										
                                            </ul>								
                                        </div>
                                        <div class="filaTablas color-a">
                                            <ul class="primera-parteTablas">	
                                                <span class="pais-pTabla esp">ESP</span>				
                                                <li class="horariosTablas">
                                                    <p>											
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                    </p>
                                                </li>										
                                            </ul>								
                                        </div>
                                        <div class="filaTablas">
                                            <ul class="primera-parteTablas">	
                                                <span class="pais-pTabla ita">ITA</span>				
                                                <li class="horariosTablas">
                                                    <p>											
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                    </p>
                                                </li>										
                                            </ul>								
                                        </div>
                                        <div class="filaTablas color-a">
                                            <ul class="primera-parteTablas">	
                                                <span class="pais-pTabla mex">Mex</span>				
                                                <li class="horariosTablas">
                                                    <p>											
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                    </p>
                                                </li>										
                                            </ul>								
                                        </div>						
                                    </div>	
                                </div>
                            </div>	
                        </div>							              
                    </div>
                </div>

                <div class="todos-los-equipos">			
                    <div class="todos-los-equiposTablas">
                        <div id="ancla2" class="grupoTablas b">
                            <div class="tablaDatos gb">
                                <div class="filtro_grupo">  
                                    <div class="simbolo-letra2 b"></div>										
                                </div>
                                <div class="contenido">					
                                    <div class="tabla-completaTablas">
                                        <div class="filaTablas color-b">					
                                            <ul class="primera-parte">				
                                                <li class="horariosTablasTitulo b">
                                                    <p>											
                                                        <span>PTS</span>
                                                        <span>PJ</span>
                                                        <span>PG</span>
                                                        <span>PE</span>
                                                        <span>PP</span>
                                                        <span>GF</span>
                                                        <span>GC</span>
                                                        <span>GD</span>
                                                    </p>
                                                </li>										
                                            </ul>		
                                        </div>
                                        <div class="filaTablas color-b2">
                                            <ul class="primera-parteTablas">	
                                                <span class="pais-pTabla col">Col</span>				
                                                <li class="horariosTablas b">
                                                    <p>											
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                    </p>
                                                </li>										
                                            </ul>								
                                        </div>
                                        <div class="filaTablas color-b">
                                            <ul class="primera-parteTablas">	
                                                <span class="pais-pTabla esp">ESP</span>				
                                                <li class="horariosTablas">
                                                    <p>											
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                    </p>
                                                </li>										
                                            </ul>								
                                        </div>
                                        <div class="filaTablas color-b2">
                                            <ul class="primera-parteTablas">	
                                                <span class="pais-pTabla ita">ITA</span>				
                                                <li class="horariosTablas">
                                                    <p>											
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                    </p>
                                                </li>										
                                            </ul>								
                                        </div>
                                        <div class="filaTablas color-b">
                                            <ul class="primera-parteTablas">	
                                                <span class="pais-pTabla mex">Mex</span>				
                                                <li class="horariosTablas">
                                                    <p>											
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                    </p>
                                                </li>										
                                            </ul>								
                                        </div>						
                                    </div>	
                                </div>
                            </div>	
                        </div>							              
                    </div>
                </div>

                <div class="todos-los-equipos">			
                    <div class="todos-los-equiposTablas">
                        <div class="grupoTablas c">
                            <div class="tablaDatos gc">
                                <div class="filtro_grupo"> 
                                    <div class="simbolo-letra2 c"></div>				   							
                                </div>
                                <div class="contenido">					
                                    <div class="tabla-completaTablas">
                                        <div class="filaTablas color-c">					
                                            <ul class="primera-parte">				
                                                <li class="horariosTablasTitulo c">
                                                    <p>											
                                                        <span>PTS</span>
                                                        <span>PJ</span>
                                                        <span>PG</span>
                                                        <span>PE</span>
                                                        <span>PP</span>
                                                        <span>GF</span>
                                                        <span>GC</span>
                                                        <span>GD</span>
                                                    </p>
                                                </li>										
                                            </ul>		
                                        </div>
                                        <div class="filaTablas color-c2">
                                            <ul class="primera-parteTablas">	
                                                <span class="pais-pTabla col">Col</span>				
                                                <li class="horariosTablas c">
                                                    <p>											
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                    </p>
                                                </li>										
                                            </ul>								
                                        </div>
                                        <div class="filaTablas color-c">
                                            <ul class="primera-parteTablas">	
                                                <span class="pais-pTabla esp">ESP</span>				
                                                <li class="horariosTablas">
                                                    <p>											
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                    </p>
                                                </li>										
                                            </ul>								
                                        </div>
                                        <div class="filaTablas color-c2">
                                            <ul class="primera-parteTablas">	
                                                <span class="pais-pTabla ita">ITA</span>				
                                                <li class="horariosTablas">
                                                    <p>											
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                    </p>
                                                </li>										
                                            </ul>								
                                        </div>
                                        <div class="filaTablas color-c">
                                            <ul class="primera-parteTablas">	
                                                <span class="pais-pTabla mex">Mex</span>				
                                                <li class="horariosTablas">
                                                    <p>											
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                    </p>
                                                </li>										
                                            </ul>								
                                        </div>						
                                    </div>	
                                </div>
                            </div>	
                        </div>
                    </div>
                </div>

                <div class="todos-los-equipos">			
                    <div class="todos-los-equiposTablas">
                        <div class="grupoTablas d">
                            <div class="tablaDatos gd">
                                <div class="filtro_grupo">	
                                    <div class="simbolo-letra2 d"></div>			 	   							
                                </div>
                                <div class="contenido">					
                                    <div class="tabla-completaTablas">
                                        <div class="filaTablas color-d">					
                                            <ul class="primera-parte">				
                                                <li class="horariosTablasTitulo d">
                                                    <p>											
                                                        <span>PTS</span>
                                                        <span>PJ</span>
                                                        <span>PG</span>
                                                        <span>PE</span>
                                                        <span>PP</span>
                                                        <span>GF</span>
                                                        <span>GC</span>
                                                        <span>GD</span>
                                                    </p>
                                                </li>										
                                            </ul>		
                                        </div>
                                        <div class="filaTablas color-d2">
                                            <ul class="primera-parteTablas">	
                                                <span class="pais-pTabla col">Col</span>				
                                                <li class="horariosTablas d">
                                                    <p>											
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                    </p>
                                                </li>										
                                            </ul>								
                                        </div>
                                        <div class="filaTablas color-d">
                                            <ul class="primera-parteTablas">	
                                                <span class="pais-pTabla esp">ESP</span>				
                                                <li class="horariosTablas">
                                                    <p>											
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                    </p>
                                                </li>										
                                            </ul>								
                                        </div>
                                        <div class="filaTablas color-d2">
                                            <ul class="primera-parteTablas">	
                                                <span class="pais-pTabla ita">ITA</span>				
                                                <li class="horariosTablas">
                                                    <p>											
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                    </p>
                                                </li>										
                                            </ul>								
                                        </div>
                                        <div class="filaTablas color-d">
                                            <ul class="primera-parteTablas">	
                                                <span class="pais-pTabla mex">Mex</span>				
                                                <li class="horariosTablas">
                                                    <p>											
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                    </p>
                                                </li>										
                                            </ul>								
                                        </div>						
                                    </div>	
                                </div>
                            </div>	
                        </div>
                    </div>
                </div>
                <div class="todos-los-equipos">			
                    <div class="todos-los-equiposTablas">
                        <div class="grupoTablas e">
                            <div class="tablaDatos ge">
                                <div class="simbolo-letra2 e"></div>			
                                <div class="filtro_grupo"> 	   							
                                </div><div class="contenido">					
                                    <div class="tabla-completaTablas">
                                        <div class="filaTablas color-e">					
                                            <ul class="primera-parte">				
                                                <li class="horariosTablasTitulo e">
                                                    <p>											
                                                        <span>PTS</span>
                                                        <span>PJ</span>
                                                        <span>PG</span>
                                                        <span>PE</span>
                                                        <span>PP</span>
                                                        <span>GF</span>
                                                        <span>GC</span>
                                                        <span>GD</span>
                                                    </p>
                                                </li>										
                                            </ul>		
                                        </div>
                                        <div class="filaTablas color-e2">
                                            <ul class="primera-parteTablas">	
                                                <span class="pais-pTabla col">Col</span>				
                                                <li class="horariosTablas e">
                                                    <p>											
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                    </p>
                                                </li>										
                                            </ul>								
                                        </div>
                                        <div class="filaTablas color-e">
                                            <ul class="primera-parteTablas">	
                                                <span class="pais-pTabla esp">ESP</span>				
                                                <li class="horariosTablas">
                                                    <p>											
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                    </p>
                                                </li>										
                                            </ul>								
                                        </div>
                                        <div class="filaTablas color-e2">
                                            <ul class="primera-parteTablas">	
                                                <span class="pais-pTabla ita">ITA</span>				
                                                <li class="horariosTablas">
                                                    <p>											
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                    </p>
                                                </li>										
                                            </ul>								
                                        </div>
                                        <div class="filaTablas color-e">
                                            <ul class="primera-parteTablas">	
                                                <span class="pais-pTabla mex">Mex</span>				
                                                <li class="horariosTablas">
                                                    <p>											
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                    </p>
                                                </li>										
                                            </ul>								
                                        </div>						
                                    </div>	
                                </div>
                            </div>	
                        </div>
                    </div>
                </div>
                <div class="todos-los-equipos">			
                    <div class="todos-los-equiposTablas">
                        <div class="grupoTablas f">
                            <div class="tablaDatos gf">
                                <div class="filtro_grupo"> 	
                                    <div class="simbolo-letra2 f"></div>			   							
                                </div>
                                <div class="contenido">					
                                    <div class="tabla-completaTablas">
                                        <div class="filaTablas color-f">					
                                            <ul class="primera-parte">				
                                                <li class="horariosTablasTitulo f">
                                                    <p>											
                                                        <span>PTS</span>
                                                        <span>PJ</span>
                                                        <span>PG</span>
                                                        <span>PE</span>
                                                        <span>PP</span>
                                                        <span>GF</span>
                                                        <span>GC</span>
                                                        <span>GD</span>
                                                    </p>
                                                </li>										
                                            </ul>		
                                        </div>
                                        <div class="filaTablas color-f2">
                                            <ul class="primera-parteTablas">	
                                                <span class="pais-pTabla col">Col</span>				
                                                <li class="horariosTablas f">
                                                    <p>											
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                    </p>
                                                </li>										
                                            </ul>								
                                        </div>
                                        <div class="filaTablas color-f">
                                            <ul class="primera-parteTablas">	
                                                <span class="pais-pTabla esp">ESP</span>				
                                                <li class="horariosTablas">
                                                    <p>											
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                    </p>
                                                </li>										
                                            </ul>								
                                        </div>
                                        <div class="filaTablas color-f2">
                                            <ul class="primera-parteTablas">	
                                                <span class="pais-pTabla ita">ITA</span>				
                                                <li class="horariosTablas">
                                                    <p>											
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                    </p>
                                                </li>										
                                            </ul>								
                                        </div>
                                        <div class="filaTablas color-f">
                                            <ul class="primera-parteTablas">	
                                                <span class="pais-pTabla mex">Mex</span>				
                                                <li class="horariosTablas">
                                                    <p>											
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                    </p>
                                                </li>										
                                            </ul>								
                                        </div>						
                                    </div>	
                                </div>
                            </div>	
                        </div>
                    </div>
                </div>
                <div class="todos-los-equipos">			
                    <div class="todos-los-equiposTablas">
                        <div class="grupoTablas g">
                            <div class="tablaDatos gg">
                                <div class="filtro_grupo"> 
                                    <div class="simbolo-letra2 g"></div>				   							
                                </div>
                                <div class="contenido">					
                                    <div class="tabla-completaTablas">
                                        <div class="filaTablas color-g">					
                                            <ul class="primera-parte">				
                                                <li class="horariosTablasTitulo g">
                                                    <p>											
                                                        <span>PTS</span>
                                                        <span>PJ</span>
                                                        <span>PG</span>
                                                        <span>PE</span>
                                                        <span>PP</span>
                                                        <span>GF</span>
                                                        <span>GC</span>
                                                        <span>GD</span>
                                                    </p>
                                                </li>										
                                            </ul>		
                                        </div>
                                        <div class="filaTablas color-g2">
                                            <ul class="primera-parteTablas">	
                                                <span class="pais-pTabla col">Col</span>				
                                                <li class="horariosTablas g">
                                                    <p>											
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                    </p>
                                                </li>										
                                            </ul>								
                                        </div>
                                        <div class="filaTablas color-g">
                                            <ul class="primera-parteTablas">	
                                                <span class="pais-pTabla esp">ESP</span>				
                                                <li class="horariosTablas">
                                                    <p>											
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                    </p>
                                                </li>										
                                            </ul>								
                                        </div>
                                        <div class="filaTablas color-g2">
                                            <ul class="primera-parteTablas">	
                                                <span class="pais-pTabla ita">ITA</span>				
                                                <li class="horariosTablas">
                                                    <p>											
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                    </p>
                                                </li>										
                                            </ul>								
                                        </div>
                                        <div class="filaTablas color-g">
                                            <ul class="primera-parteTablas">	
                                                <span class="pais-pTabla mex">Mex</span>				
                                                <li class="horariosTablas">
                                                    <p>											
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                    </p>
                                                </li>										
                                            </ul>								
                                        </div>						
                                    </div>	
                                </div>
                            </div>	
                        </div>
                    </div>
                </div>
                <div class="todos-los-equipos">			
                    <div class="todos-los-equiposTablas">
                        <div class="grupoTablas h">
                            <div class="tablaDatos gh">
                                <div class="filtro_grupo">
                                    <div class="simbolo-letra2 h"></div>											   							
                                </div>
                                <div class="contenido">					
                                    <div class="tabla-completaTablas">
                                        <div class="filaTablas color-h">					
                                            <ul class="primera-parte">				
                                                <li class="horariosTablasTitulo h">
                                                    <p>											
                                                        <span>PTS</span>
                                                        <span>PJ</span>
                                                        <span>PG</span>
                                                        <span>PE</span>
                                                        <span>PP</span>
                                                        <span>GF</span>
                                                        <span>GC</span>
                                                        <span>GD</span>
                                                    </p>
                                                </li>										
                                            </ul>		
                                        </div>
                                        <div class="filaTablas color-h2">
                                            <ul class="primera-parteTablas">	
                                                <span class="pais-pTabla col">Col</span>				
                                                <li class="horariosTablas h">
                                                    <p>											
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                    </p>
                                                </li>										
                                            </ul>								
                                        </div>
                                        <div class="filaTablas color-h">
                                            <ul class="primera-parteTablas">	
                                                <span class="pais-pTabla esp">ESP</span>				
                                                <li class="horariosTablas">
                                                    <p>											
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                    </p>
                                                </li>										
                                            </ul>								
                                        </div>
                                        <div class="filaTablas color-h2">
                                            <ul class="primera-parteTablas">	
                                                <span class="pais-pTabla ita">ITA</span>				
                                                <li class="horariosTablas">
                                                    <p>											
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                    </p>
                                                </li>										
                                            </ul>								
                                        </div>
                                        <div class="filaTablas color-h">
                                            <ul class="primera-parteTablas">	
                                                <span class="pais-pTabla mex">Mex</span>				
                                                <li class="horariosTablas">
                                                    <p>											
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                        <span>10</span>
                                                    </p>
                                                </li>										
                                            </ul>								
                                        </div>						
                                    </div>	
                                </div>
                            </div>	
                        </div>
                    </div>
                </div>
            </div>
            </br>


            <?php print $this->footer(); ?>

            <a class="btnVerGrupos posiciones" data-animation="fade" data-reveal-id="a1" href="#a1">Ver por grupos</a>

            <div class="botonesInferiores posiciones">
                <a href="/mundial-brasil-2014/calendario">Calendario</a>
                <a href="grupos">Grupos</a>
            </div>

        </div>
        <?php print $this->menu(); ?>
    </div>




    <!-- jQuery -->
    <script src="/mundial-brasil-2014/js/jquery.min_1.js"></script>
    <script>window.jQuery || document.write('<script src="js/libs/jquery-1.7.min.js">\x3C/script>')</script>

    <!-- FlexSlider -->
    <script defer src="/mundial-brasil-2014/js/jsCalendario/jquery.flexslider.js"></script>

    <script type="text/javascript">

        $(window).load(function() {
            $('.flexslider').flexslider({
                animation: "slide",
                directionNav: false,
                slideshow: false,
                start: function(slider) {
                    $('body').removeClass('loading');
                }
            });
        });
    </script>

    <script type="text/javascript">
        $(window).scroll(function() {
            var posicion = $(window).scrollTop();
            if (posicion >= 80) {
                $('header').addClass('fijo');
                $('.top-bar ul li').addClass('fijo');
                $('.secciones').addClass('fix');
            }
            else {
                $('header').removeClass('fijo');
                $('.top-bar ul li').removeClass('fijo');
                $('.secciones').removeClass('fix');
            }
        });
    </script>



    <!-- Optional FlexSlider Additions -->
    <script src="/mundial-brasil-2014/js/jsCalendario/jquery.easing.js"></script>
    <script src="/mundial-brasil-2014/js/jsCalendario/jquery.mousewheel.js"></script>
    <script src="/mundial-brasil-2014/js/jsCalendario/mundial-mobile.js"></script>


    <!-- jquuery anclas grupos --->
    <script type="text/javascript" src="/mundial-brasil-2014/js/jquery.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            //nos desplazamos entre todos los divs
            $('a.btnTabla.a').click(function(e) {
                e.preventDefault();
                enlace = $(this).attr('href');
                $('html, body').animate({
                    scrollTop: $(enlace).offset().top - 350
                }, 1000);
            });

            $('a.btnTabla.b').click(function(e) {
                $('html, body').animate({scrollTop: 330}, 2000);
                return false;
            });

            $('a.btnTabla.c').click(function(e) {
                $('html, body').animate({scrollTop: 540}, 2000);
                return false;
            });

            $('a.btnTabla.d').click(function(e) {
                $('html, body').animate({scrollTop: 745}, 2000);
                return false;
            });

            $('a.btnTabla.e').click(function(e) {
                $('html, body').animate({scrollTop: 950}, 2000);
                return false;
            });

            $('a.btnTabla.f').click(function(e) {
                $('html, body').animate({scrollTop: 1160}, 2000);
                return false;
            });
            $('a.btnTabla.g').click(function(e) {
                $('html, body').animate({scrollTop: 1370}, 2000);
                return false;
            });
            $('a.btnTabla.h').click(function(e) {
                $('html, body').animate({scrollTop: 1575}, 2000);
                return false;
            });

        });
    </script>

    <?php
    $referer = '';
    if (isset($_SERVER['HTTP_REFERER'])):
        $referer = $_SERVER['HTTP_REFERER'];
    endif;
    ?>
    <!-- SiteCatalyst code version: H.25.3.
         Copyright 1996-2013 Adobe, Inc. All Rights Reserved
         More info available at http://www.omniture.com -->
    <img src="http://eltiempo.112.2o7.net/b/ss/eltiempoeltiempomovil,eltiempoglobal/5/H.25.3--WAP/489?pageName=Posiciones&ch=calendario&r=<?php print $referer; ?>" height="1" width="1" border="0" alt="" style="position:absolute"></img>
    <!-- End SiteCatalyst code version: H.25.3. -->

</body>
