<div class="secciones">
    <div id="overlay" class="overlay"></div>
    <?php print $this->pauta('9703', '432763');?>
    <section class="gal-ppal">
        <?php print $this->carouselPpal($notas);?>
    </section>
      
    <?php print $this->partial('mundial/index/calendario');?>
   
    <?php print $this->modulosHome('modulo-notas-home','Selección Colombia', 'ac-7', 'accordion-7', 'colombia', 'home_colombia');?>
    
    <?php print $this->modulosHome('modulo-notas-home','Ver equipos del mundo', 'ac-2', 'accordion-2', 'mundo', 'home_mundo');?>
    
    <?php print $this->pauta('9704', '432763');?>
    
    <?php print $this->modulosHome('modulo-notas-home','Opinión de los Expertos', 'ac-3', 'accordion-3', 'opinion', 'home_opinion');?>
    
    <?php print $this->modulosHome('modulo-notas-home','Ver multimedia', 'ac-4', 'accordion-4', 'multimedia', 'home_multimedia');?>
    
    <?php print $this->pauta('9702', '432763');?>
    
    <?php print $this->modulosHome('modulo-notas-home','Curiosidades', 'ac-6', 'accordion-6', 'curiosidades', 'home_curiosidades');?>
</div>

