<div class="equipos">
    <a href="#">Equipos</a>
    <div class="drop_equipos">
        <ul>
            <li><h3>Grupo A</h3></li>
            <li><a href="/mundial-brasil-2014/ficha-de-equipo/brasil"><h3 class="Bra">Brasil</h3></a></li>
            <li><a href="/mundial-brasil-2014/ficha-de-equipo/mexico"><h3 class="Mex">México</h3></a></li>
            <li><a href="/mundial-brasil-2014/ficha-de-equipo/croacia"><h3 class="Cro">Croacia</h3></a></li>
            <li><a href="/mundial-brasil-2014/ficha-de-equipo/camerun"><h3 class="Cam">Camerún</h3></a></li>
        </ul>
        <ul>
            <li><h3>Grupo B</h3></li>
            <li><a href="/mundial-brasil-2014/ficha-de-equipo/espana"><h3 class="Esp">España</h3></a></li>
            <li><a href="/mundial-brasil-2014/ficha-de-equipo/chile"><h3 class="Chi">Chile</h3></a></li>
            <li><a href="/mundial-brasil-2014/ficha-de-equipo/holanda"><h3 class="Hol">Holanda</h3></a></li>
            <li><a href="/mundial-brasil-2014/ficha-de-equipo/australia"><h3 class="Aus">Australia</h3></a></li>
        </ul>
        <ul>
            <li><h3>Grupo C</h3></li>
            <li><a href="/mundial-brasil-2014/ficha-de-equipo/colombia"><h3 class="Col">Colombia</h3></a></li>
            <li><a href="/mundial-brasil-2014/ficha-de-equipo/costa-de-marfil"><h3 class="Cdm">Costa de Marfil</h3></a></li>
            <li><a href="/mundial-brasil-2014/ficha-de-equipo/grecia"><h3 class="Gre">Grecia</h3></a></li>
            <li><a href="/mundial-brasil-2014/ficha-de-equipo/japon"><h3 class="Jap">Japón</h3></a></li>
        </ul>
        <ul>
            <li><h3>Grupo D</h3></li>
            <li><a href="/mundial-brasil-2014/ficha-de-equipo/uruguay"><h3 class="Uru">Uruguay</h3></a></li>
            <li><a href="/mundial-brasil-2014/ficha-de-equipo/inglaterra"><h3 class="Ing">Inglaterra</h3></a></li>
            <li><a href="/mundial-brasil-2014/ficha-de-equipo/costa-rica"><h3 class="Cri">Costa Rica</h3></a></li>
            <li><a href="/mundial-brasil-2014/ficha-de-equipo/italia"><h3 class="Ita">Italia</h3></a></li>
        </ul>
        <ul>
            <li><h3>Grupo E</h3></li>
            <li><a href="/mundial-brasil-2014/ficha-de-equipo/suiza"><h3 class="Sui">Suiza</h3></a></li>
            <li><a href="/mundial-brasil-2014/ficha-de-equipo/ecuador"><h3 class="Ecu">Ecuador</h3></a></li>
            <li><a href="/mundial-brasil-2014/ficha-de-equipo/francia"><h3 class="Fra">Francia</h3></a></li>
            <li><a href="/mundial-brasil-2014/ficha-de-equipo/honduras"><h3 class="Hon">Honduras</h3></a></li>
        </ul>
        <ul>
            <li><h3>Grupo F</h3></li>
            <li><a href="/mundial-brasil-2014/ficha-de-equipo/argentina"><h3 class="Arg">Argentina</h3></a></li>
            <li><a href="/mundial-brasil-2014/ficha-de-equipo/bosnia"><h3 class="Bos">Bosnia</h3></a></li>
            <li><a href="/mundial-brasil-2014/ficha-de-equipo/iran"><h3 class="Irn">Irán</h3></a></li>
            <li><a href="/mundial-brasil-2014/ficha-de-equipo/nigeria"><h3 class="Nig">Nigeria</h3></a></li>
        </ul>
        <ul>
            <li><h3>Grupo G</h3></li>
            <li><a href="/mundial-brasil-2014/ficha-de-equipo/alemania"><h3 class="Ale">Alemania</h3></a></li>
            <li><a href="/mundial-brasil-2014/ficha-de-equipo/portugal"><h3 class="Por">Portugal</h3></a></li>
            <li><a href="/mundial-brasil-2014/ficha-de-equipo/ghana"><h3 class="Gha">Ghana</h3></a></li>
            <li><a href="/mundial-brasil-2014/ficha-de-equipo/estados-unidos"><h3 class="Eua">Estados Unidos</h3></a></li>
        </ul>
        <ul>
            <li><h3>Grupo H</h3></li>
            <li><a href="/mundial-brasil-2014/ficha-de-equipo/belgica"><h3 class="Bel">Bélgica</h3></a></li>
            <li><a href="/mundial-brasil-2014/ficha-de-equipo/argelia"><h3 class="Agl">Argelia</h3></a></li>
            <li><a href="/mundial-brasil-2014/ficha-de-equipo/rusia"><h3 class="Rus">Rusia</h3></a></li>
            <li><a href="/mundial-brasil-2014/ficha-de-equipo/corea"><h3 class="Cor">Corea</h3></a></li>
        </ul>
    </div>
</div>