<section class="tabla_clasificacion">
    <div class="tit_tabla">
        <h3>Nomina Oficial de Equipo</h3>
    </div>
    <div class="container_tabla">                    	                     

        <div id="tabs">

            <div id="tabs-1" class="botonesNomina">
                <div class="contenidoNomina">
                    <li>7. Jhonathan TORO</li>
                    <li>7. Jhonathan TORO</li>
                    <li>7. Jhonathan TORO</li>
                    <li>7. Jhonathan TORO</li>
                    <li>7. Jhonathan TORO</li>
                </div>
            </div>
            <div id="tabs-2" class="botonesNomina">
                <div class="contenidoNomina">
                    <li>4. Yefri DUQUE</li>
                    <li>4. Yefri DUQUE</li>
                    <li>4. Yefri DUQUE</li>
                    <li>4. Yefri DUQUE</li>
                </div>
            </div>
            <div id="tabs-3" class="botonesNomina">
                <div class="contenidoNomina">
                    <li>9. Andres REYES</li>
                    <li>9. Andres REYES</li>
                    <li>9. Andres REYES</li>
                    <li>9. Andres REYES</li>
                    <li>9. Andres REYES</li>
                </div>
            </div>

            <div id="tabs-4" class="botonesNomina">
                <div class="contenidoNomina">
                    <li>10. Angellott CARO</li>
                    <li>10. Angellott CARO</li>
                    <li>10. Angellott CARO</li>
                    <li>10. Angellott CARO</li>
                </div>
            </div>

            <div id="tabs-5" class="botonesNomina">
                <div class="contenidoNomina">
                    <li>11. Alejandro SERNA</li>
                    <li>11. Alejandro SERNA</li>
                    <li>11. Alejandro SERNA</li>
                    <li>11. Alejandro SERNA</li>
                    <li>11. Alejandro SERNA</li>
                </div>
            </div>


            <ul>
                <li><a class="menuNomina active" href="#tabs-1" >Guardametas</a></li>
                <li><a class="menuNomina" href="#tabs-2">Defensas</a></li>
                <li><a class="menuNomina" href="#tabs-3">Mediocampista</a></li>
                <li><a class="menuNomina" href="#tabs-4">Delanteros</a></li>
                <li><a class="menuNomina" href="#tabs-5">Entrenador</a></li>
            </ul>                         
        </div>
    </div> 
</section>