<div class="bloqueDirectorTecnico">
    <div class="container_otras_gal">
        <div class="tit">
            <h3>Director Técnico</h3>
        </div>
    </div>	
    <img alt="<?php print $tecnico['nombre'];?>" title="<?php print $tecnico['nombre'];?>" src="<?php print $tecnico['imagen'];?>" />
    <h1><?php print $tecnico['nombre'];?></h1>
    <p><?php print $tecnico['descripcion'];?></p>
</div>