<?php

?>
<footer>
            <div class="container_footer row">
                <div class="promoFooter">
                    <a class="suscribase" href="#">Suscríbete y disfruta de un mundo de información de la mano de EL TIEMPO</a>
                    <a href="#" class="versiones">Conozca nuestras versiones</a>
                </div>
                <div class="contenidoFooter">
                    <section class="secciones">
                        <h4>Secciones</h4>
                        <ul>
                            <li><h3><a href="#">Colombia</a></h3></li>
                            <li><h3><a href="#">Politica</a></h3></li>
                            <li><h3><a href="#">Justicia</a></h3></li>
                            <li><h3><a href="#">Mundo</a></h3></li>
                            <li><h3><a href="#">Deportes</a></h3></li>
                        </ul>
                        
                        <ul>
                            <li><h3><a href="#">Economía</a></h3></li>
                            <li><h3><a href="#">Opinión</a></h3></li>
                            <li><h3><a href="#">Tecnología</a></h3></li>
                            <li><h3><a href="#">Entretenimiento</a></h3></li>
                        </ul>
                        
                        <ul>
                            <li><h3><a href="#">Gente</a></h3></li>
                            <li><h3><a href="#">Vida de Hoy</a></h3></li>
                            <li><h3><a href="#">Reportero Ciudadano</a></h3></li>
                            <li><h3><a href="#">Blogs</a></h3></li>
                        </ul>
                    </section>
                    <section class="ayuda">
                        <h4>¿Necesita Ayuda?</h4>
                        <ul>
                            <li><a href="#">FAQ</a></li>
                            <li><a href="#">Contáctenos</a></li>
                            <li><a href="#">Chat</a></li>
                            <li><a href="#">Llámenos al 018000xxxxx</a></li>
                            <li><a href="#">Centros de ayuda</a></li>
                        </ul>
                    </section>
                    <section class="servicios">
                        <h4>Servicios</h4>
                        <ul>
                            <li><h3><a href="#">Horóscopo</a></h3></li>
                            <li><h3><a href="#">Puerto Astral</a></h3></li>
                            <li><h3><a href="#">Pico y Placa</a></h3></li>
                            <li><h3><a href="#">Clima</a></h3></li>
                            <li><h3><a href="#">Crucigrama</a></h3></li>
                        </ul>
                    </section>
                    <div>
                        <div class="elTiempo">
                            <h3 class="activo"><a href="#">El Tiempo Casa Editorial</a></h3>
                        </div>
                        <div class="revistas">
                            <h3><a href="#">Revistas</a></h3>
                        </div>
                        <div class="nuestrosPortales">
                            <h3><a href="#">Nuestros portales</a></h3>
                        </div>
                        
                        <div class="desplegable_secciones activo">
                            <ul>
                                <li><h3><a href="#">Paute con nosotros</a></h3></li>
                                <li><h3><a href="#">Trabaje con nosotros</a></h3></li>
                                <li><h3><a href="#">Quienes somos</a></h3></li>
                            </ul>
                            <ul>
                                <li><h3><a href="#">Contáctenos</a></h3></li>
                                <li><h3><a href="#">Centros de venta</a></h3></li>
                                <li><h3><a href="#">Publicidad politica</a></h3></li>
                            </ul>
                            <ul>
                                <li><h3><a href="#">Colecciones</a></h3></li>
                                <li><h3><a href="#">Vivamos</a></h3></li>
                                <li><h3><a href="#">Suscripciones</a></h3></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="terminos">
                    <a href="#">Términos y Condiciones.</a>
                    <a class="logo1">
                        <figure><img src="" alt="" /></figure>
                        <p>Miembro de Grupo de Diarios de América</p>
                    </a>
                    <a class="logo2">
                        <figure><img src="" alt="" /></figure>
                        <p>Miembro de Interactive Advertisement Bureau</p>
                    </a>
                </div>
                <div class="copy">
                    <p>COPYRIGHT © 2013 EL TIEMPO Casa Editorial. Prohibida su reproducción total o parcial, así como su traducción a cualquier idioma sin autorización escrita de su titular. ELTIEMPO.com todas las noticias principales de Colombia y el Mundo</p>
                    <h5>ELTIEMPO.com todas las noticias principales de Colombia y el Mundo</h5>
                </div>
            </div>
            <!-- End container_footer -->
        </footer>