<header>
            <div class="row header">
                <div class="container_header">
                    <ul class="top_bar registro">
                        <li class="suscribete">Suscríbete</li>
                    </ul>
                    
                    <!-- End top_bar -->
                    
                    <div class="content_logo">
                        <h1 class="logo"><a href="#">EL TIEMPO.com</a></h1>
                        <time datetime="2013-02-18" class="time">Lunes 18 de febrero de 2013</time>
                    </div>
                
                    <!-- End content_logo -->
                    <div class="content-pauta-header"><a>Pauta Header</a></div>
                    
                    <!-- End pauta -->
                    
                    <nav class="menu">
                        <ul class="content-menu">
                            <li class="main">
                                <div id="dd" class="wrapper-dropdown" tabindex="1">
                                    <ul class="dropdown">
                                        <li><h3><a href="#">Portada</a></h3></li>
                                        <li><h3><a href="#">Otras secciones</a></h3></li>
                                        <li><h3><a href="#">Colombia</a></h3></li>
                                        <li><h3><a href="#">Tecnologia</a></h3></li>
                                        <li><h3><a href="#">Vida de hoy</a></h3></li>
                                        <li><h3><a href="#">Salud</a></h3></li>
                                        <li><h3><a href="#">Educación</a></h3></li>
                                        <li><h3><a href="#">Viajar</a></h3></li>
                                        <li><h3><a href="#">Gente</a></h3></li>
                                        <li><h3><a href="#">Motor</a></h3></li>
                                        <li><h3><a href="#">Carrusel</a></h3></li>
                                        <li><h3><a href="#">Elenco</a></h3></li>
                                        <li><h3><a href="#">Lecturas</a></h3></li>
                                    </ul>
                                </div>
                                <!-- End dropdown -->
                            </li>
                            <!--<li><h3><a href="#">Portada</a></h3></li>-->
                            <li><h3><a href="#">Opinión</a></h3></li>
                            <li><h3><a href="#">Política</a></h3></li>
                            <li><h3><a href="#">Justicia</a></h3></li>
                            <li><h3><a href="#">Bogotá</a></h3></li>
                            <li><h3><a href="#">Cultura</a></h3></li>
                            <li><h3><a href="#">Deportes</a></h3></li>  
                            <li><h3><a href="#">Economía</a></h3></li> 
                            <li><h3><a href="#">Mundo</a></h3></li>                     
                            <li><h3><a href="#">Premium</a></h3></li>
                            <li><h3><a href="#">Clasificados</a></h3></li>
                            <li class="buscador"><h3><a class="ico-buscar" href="#"></a></h3></li>
                            <li class="conectate"><h3><a class="user" href="#">Conéctate</a></h3></li>
                            
                        </ul>                       
                    </nav>
                    <!-- End nav -->
                    <div class="content-buscador">
                    <form>
                        <input type="text" name="buscador" placeholder="Buscar" autocomplete="on" class="buscador" /><a class="btn_cerrar"href="#">x</a>
                    </form>
                    </div>
                    
                </div>
                <!-- End container header -->
                
                <div class="bottom_bar">
                    <!--<h3 class="bot_temas"><a href="#">Temas del día +</a></h3>-->
                    <ul class="temas">
                        <li class="cabeza_temas"><a href="#">Temas del día </a></li>
                        <li><a href="#">Farc</a></li>
                        <li><a href="#">Corte constitucional</a></li>
                        <li><a href="#">Eliminatorias mundial</a></li>
                        <li><a href="#">Seleccion Colomobia</a></li>
                        <li><a href="#">Operación Jaque</a></li>
                        <li><a href="#">Papa Francisco</a></li>
                        <li><a href="#">Movilidad</a></li>
                        <li class="mas_temas"><a href="#">Ver más temas del día</a></li>
                        
                    </ul>
                    <!-- End temas -->
                </div>
                <!-- End bottom_bar -->
            </div>
        </header>